#!/usr/bin/env python3
"""
plot_profile.py — TBox 应用资源画像 HTML 生成器 (内嵌 csv_verify)
用法: python3 plot_profile.py <profile_dir>
"""
import sys, os, csv, subprocess, base64

_CSV_B64 = """f0VMRgIBAQAAAAAAAAAAAAMAPgABAAAAEBcAAAAAAABAAAAAAAAAAAg8AAAAAAAAAAAAAEAAOAANAEAAHwAeAAYAAAAEAAAAQAAAAAAAAABAAAAAAAAAAEAAAAAAAAAA2AIAAAAAAADYAgAAAAAAAAgAAAAAAAAAAwAAAAQAAAAYAwAAAAAAABgDAAAAAAAAGAMAAAAAAAAcAAAAAAAAABwAAAAAAAAAAQAAAAAAAAABAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOAMAAAAAAAA4AwAAAAAAAAAEAAAAAAAAAEAAAAFAAAAABAAAAAAAAAAEAAAAAAAAAAQAAAAAAAA6Q0AAAAAAADpDQAAAAAAAAAQAAAAAAAAAQAAAAQAAAAAIAAAAAAAAAAgAAAAAAAAACAAAAAAAAC0BAAAAAAAALQEAAAAAAAAABAAAAAAAAABAAAABgAAANgsAAAAAAAA2DwAAAAAAADYPAAAAAAAADgDAAAAAAAAWAMAAAAAAAAAEAAAAAAAAAIAAAAGAAAA6CwAAAAAAADoPAAAAAAAAOg8AAAAAAAAAAIAAAAAAAAAAgAAAAAAAAgAAAAAAAAABAAAAAQAAAA4AwAAAAAAADgDAAAAAAAAOAMAAAAAAAAwAAAAAAAAADAAAAAAAAAACAAAAAAAAAAEAAAABAAAAGgDAAAAAAAAaAMAAAAAAABoAwAAAAAAAEQAAAAAAAAARAAAAAAAAAAEAAAAAAAAAFPldGQEAAAAOAMAAAAAAAA4AwAAAAAAADgDAAAAAAAAMAAAAAAAAAAwAAAAAAAAAAgAAAAAAAAAUOV0ZAQAAAA0IgAAAAAAADQiAAAAAAAANCIAAAAAAABUAAAAAAAAAFQAAAAAAAAABAAAAAAAAABR5XRkBgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAFLldGQEAAAA2CwAAAAAAADYPAAAAAAAANg8AAAAAAAAKAMAAAAAAAAoAwAAAAAAAAEAAAAAAAAAL2xpYjY0L2xkLWxpbnV4LXg4Ni02NC5zby4yAAAAAAAEAAAAIAAAAAUAAABHTlUAAgAAwAQAAAADAAAAAAAAAAKAAMAEAAAAAQAAAAAAAAAEAAAAFAAAAAMAAABHTlUA7JPq5Gd/o6eycAdyDPKITTKEvLUEAAAAEAAAAAEAAABHTlUAAAAAAAMAAAACAAAAAAAAAAAAAAACAAAAIAAAAAEAAAAGAAAAAAGBAAAAAAIgAAAAIQAAANFlzm058oscAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA5AAAABIAAAAAAAAAAAAAAAAAAAAAAAAApAAAABIAAAAAAAAAAAAAAAAAAAAAAAAAAQAAACAAAAAAAAAAAAAAAAAAAAAAAAAAfwAAABIAAAAAAAAAAAAAAAAAAAAAAAAAawAAABIAAAAAAAAAAAAAAAAAAAAAAAAAeAAAABIAAAAAAAAAAAAAAAAAAAAAAAAAvwAAABIAAAAAAAAAAAAAAAAAAAAAAAAARgAAABIAAAAAAAAAAAAAAAAAAAAAAAAAZQAAABIAAAAAAAAAAAAAAAAAAAAAAAAAEAAAACAAAAAAAAAAAAAAAAAAAAAAAAAA6gAAABIAAAAAAAAAAAAAAAAAAAAAAAAALAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAIAEAABIAAAAAAAAAAAAAAAAAAAAAAAAAPAEAABIAAAAAAAAAAAAAAAAAAAAAAAAAGAEAABIAAAAAAAAAAAAAAAAAAAAAAAAA7wAAABIAAAAAAAAAAAAAAAAAAAAAAAAANQEAABIAAAAAAAAAAAAAAAAAAAAAAAAAuQAAABIAAAAAAAAAAAAAAAAAAAAAAAAA9gAAABIAAAAAAAAAAAAAAAAAAAAAAAAAKAEAABIAAAAAAAAAAAAAAAAAAAAAAAAARAEAABIAAAAAAAAAAAAAAAAAAAAAAAAAsgAAABIAAAAAAAAAAAAAAAAAAAAAAAAAxQAAABIAAAAAAAAAAAAAAAAAAAAAAAAA2wAAABIAAAAAAAAAAAAAAAAAAAAAAAAAAwEAABIAAAAAAAAAAAAAAAAAAAAAAAAAhQAAABIAAAAAAAAAAAAAAAAAAAAAAAAAzAAAABIAAAAAAAAAAAAAAAAAAAAAAAAALgEAABIAAAAAAAAAAAAAAAAAAAAAAAAAkgAAABIAAAAAAAAAAAAAAAAAAAAAAAAAjQAAABIAAAAAAAAAAAAAAAAAAAAAAAAAUQAAABIAAAAAAAAAAAAAAAAAAAAAAAAAVgAAACIAAAAAAAAAAAAAAAAAAAAAAAAAEQEAABEAGgAgQAAAAAAAAAgAAAAAAAAAAF9fZ21vbl9zdGFydF9fAF9JVE1fZGVyZWdpc3RlclRNQ2xvbmVUYWJsZQBfSVRNX3JlZ2lzdGVyVE1DbG9uZVRhYmxlAEVWUF9zaGEyNTYASE1BQwBfX2N4YV9maW5hbGl6ZQBmZ2V0cwBfX3ByaW50Zl9jaGsAbWFsbG9jAGZzZWVrAHN0cmNzcG4Ac3RhdABfX2xpYmNfc3RhcnRfbWFpbgBfX2ZwcmludGZfY2hrAHN0cmNtcABmcHV0cwBmb3BlbgBmY2xvc2UAX19zbnByaW50Zl9jaGsAY2xvc2VkaXIAZnRlbGwAZnJlZQBzdHJzdHIAX19zdHJjcHlfY2hrAF9fc3ByaW50Zl9jaGsAc3RkZXJyAHN0cnJjaHIAb3BlbmRpcgBmcmVhZABwZXJyb3IAcmV3aW5kAHJlYWRkaXIAX19zdGFja19jaGtfZmFpbABsaWJjcnlwdG8uc28uMwBsaWJjLnNvLjYAT1BFTlNTTF8zLjAuMABHTElCQ18yLjMzAEdMSUJDXzIuMzQAR0xJQkNfMi40AEdMSUJDXzIuMy40AEdMSUJDXzIuMi41AAAAAgADAAEAAgADAAIAAgAEAAIAAQACAAEAAgACAAIAAgACAAIAAwACAAUAAgACAAIAAwACAAMAAgAGAAcABAACAAIAAQABAFUBAAAQAAAAIAAAACArcAYAAAQAbgEAAAAAAAABAAUAZAEAABAAAAAAAAAAs5GWBgAABwB8AQAAEAAAALSRlgYAAAYAhwEAABAAAAAUaWkNAAAFAJIBAAAQAAAAdBlpCQAAAwCcAQAAEAAAAHUaaQkAAAIAqAEAAAAAAADYPAAAAAAAAAgAAAAAAAAA8BcAAAAAAADgPAAAAAAAAAgAAAAAAAAAsBcAAAAAAAAIQAAAAAAAAAgAAAAAAAAACEAAAAAAAADYPwAAAAAAAAYAAAADAAAAAAAAAAAAAADgPwAAAAAAAAYAAAAKAAAAAAAAAAAAAADoPwAAAAAAAAYAAAAMAAAAAAAAAAAAAADwPwAAAAAAAAYAAAAgAAAAAAAAAAAAAAD4PwAAAAAAAAYAAAAdAAAAAAAAAAAAAAAgQAAAAAAAAAUAAAAhAAAAAAAAAAAAAAAAPwAAAAAAAAcAAAABAAAAAAAAAAAAAAAIPwAAAAAAAAcAAAACAAAAAAAAAAAAAAAQPwAAAAAAAAcAAAAEAAAAAAAAAAAAAAAYPwAAAAAAAAcAAAAFAAAAAAAAAAAAAAAgPwAAAAAAAAcAAAAGAAAAAAAAAAAAAAAoPwAAAAAAAAcAAAAHAAAAAAAAAAAAAAAwPwAAAAAAAAcAAAAIAAAAAAAAAAAAAAA4PwAAAAAAAAcAAAAJAAAAAAAAAAAAAABAPwAAAAAAAAcAAAALAAAAAAAAAAAAAABIPwAAAAAAAAcAAAANAAAAAAAAAAAAAABQPwAAAAAAAAcAAAAOAAAAAAAAAAAAAABYPwAAAAAAAAcAAAAPAAAAAAAAAAAAAABgPwAAAAAAAAcAAAAQAAAAAAAAAAAAAABoPwAAAAAAAAcAAAARAAAAAAAAAAAAAABwPwAAAAAAAAcAAAASAAAAAAAAAAAAAAB4PwAAAAAAAAcAAAATAAAAAAAAAAAAAACAPwAAAAAAAAcAAAAUAAAAAAAAAAAAAACIPwAAAAAAAAcAAAAVAAAAAAAAAAAAAACQPwAAAAAAAAcAAAAWAAAAAAAAAAAAAACYPwAAAAAAAAcAAAAXAAAAAAAAAAAAAACgPwAAAAAAAAcAAAAYAAAAAAAAAAAAAACoPwAAAAAAAAcAAAAZAAAAAAAAAAAAAACwPwAAAAAAAAcAAAAaAAAAAAAAAAAAAAC4PwAAAAAAAAcAAAAbAAAAAAAAAAAAAADAPwAAAAAAAAcAAAAcAAAAAAAAAAAAAADIPwAAAAAAAAcAAAAeAAAAAAAAAAAAAADQPwAAAAAAAAcAAAAfAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPMPHvpIg+wISIsFyS8AAEiFwHQC/9BIg8QIwwAAAAAA/zXKLgAA8v8lyy4AAA8fAPMPHvpoAAAAAPLp4f///5DzDx76aAEAAADy6dH///+Q8w8e+mgCAAAA8unB////kPMPHvpoAwAAAPLpsf///5DzDx76aAQAAADy6aH///+Q8w8e+mgFAAAA8umR////kPMPHvpoBgAAAPLpgf///5DzDx76aAcAAADy6XH///+Q8w8e+mgIAAAA8ulh////kPMPHvpoCQAAAPLpUf///5DzDx76aAoAAADy6UH///+Q8w8e+mgLAAAA8ukx////kPMPHvpoDAAAAPLpIf///5DzDx76aA0AAADy6RH///+Q8w8e+mgOAAAA8ukB////kPMPHvpoDwAAAPLp8f7//5DzDx76aBAAAADy6eH+//+Q8w8e+mgRAAAA8unR/v//kPMPHvpoEgAAAPLpwf7//5DzDx76aBMAAADy6bH+//+Q8w8e+mgUAAAA8umh/v//kPMPHvpoFQAAAPLpkf7//5DzDx76aBYAAADy6YH+//+Q8w8e+mgXAAAA8ulx/v//kPMPHvpoGAAAAPLpYf7//5DzDx76aBkAAADy6VH+//+Q8w8e+mgaAAAA8ulB/v//kPMPHvry/yUFLgAADx9EAADzDx768v8lBS0AAA8fRAAA8w8e+vL/Jf0sAAAPH0QAAPMPHvry/yX1LAAADx9EAADzDx768v8l7SwAAA8fRAAA8w8e+vL/JeUsAAAPH0QAAPMPHvry/yXdLAAADx9EAADzDx768v8l1SwAAA8fRAAA8w8e+vL/Jc0sAAAPH0QAAPMPHvry/yXFLAAADx9EAADzDx768v8lvSwAAA8fRAAA8w8e+vL/JbUsAAAPH0QAAPMPHvry/yWtLAAADx9EAADzDx768v8lpSwAAA8fRAAA8w8e+vL/JZ0sAAAPH0QAAPMPHvry/yWVLAAADx9EAADzDx768v8ljSwAAA8fRAAA8w8e+vL/JYUsAAAPH0QAAPMPHvry/yV9LAAADx9EAADzDx768v8ldSwAAA8fRAAA8w8e+vL/JW0sAAAPH0QAAPMPHvry/yVlLAAADx9EAADzDx768v8lXSwAAA8fRAAA8w8e+vL/JVUsAAAPH0QAAPMPHvry/yVNLAAADx9EAADzDx768v8lRSwAAA8fRAAA8w8e+vL/JT0sAAAPH0QAAPMPHvry/yU1LAAADx9EAADzDx76QVdBVkFVQVRVU0iJ80iB7LgEAABkSIsEJSgAAABIiYQkqAQAADHAg/8BD46xAgAAjVf+SI1GCDHtRTHkSI1M1hDrJGYPH4QAAAAAAIB6AXF1HYB6AgB1F0iDwAhBvAEAAABIOcF0FEiLEIA6LXTdSIPACEiJ1Ug5wXXsSIXtD4RdAgAASI10JBBIie/oS////4XAD4UkAgAAi0QkKCUA8AAARYXkD4WgAAAASItTCD0AQAAAD4SgAAAASI01FgwAAL8BAAAAMcDor/3//0iLewjohgMAAIPAAoPg/Q+EdQEAAEiNNVwNAAC/AQAAADHAQb0BAAAA6IH9//9BvAEAAABEielEieJIjTX6CwAAMcC/AQAAAOhi/f//McBFheQPn8BIi5QkqAQAAGRIKxQlKAAAAA+FKwIAAEiBxLgEAABbXUFcQV1BXkFfwz0AQAAAD4U7AQAASItTCEiJ1+h6/f//SInFSIXAD4TWAQAASItTCEiNNTwLAAAxwEUx7b8BAAAARTHkTI01PwsAAOjq/P//Zi4PH4QAAAAAAEiJ7+hI/f//SIXAD4SFAAAATI14E74uAAAATIn/6D79//9IicdIhcB01kyJ9uie/f//hcB1ykyLSwi5AAQAAEiNvCSgAAAASIPsCEFXugEAAAC+AAQAAEyNBdcKAABIiXwkGOi4/f//SIt8JBjoTgIAAFpIie9Zg8ACg+D9g/gBQYPc/0GDxQHow/z//0iFwA+Fe////0iJ7+hS/f//McC/AQAAAEiNNf0LAADoL/z//0WF5HQe6ar+//9IjTXnCwAAvwEAAAAxwEG9AQAAAOgM/P//RInpRInqSI01cQoAADHAvwEAAABFMeTo8Pv//+mJ/v//SInv6JMFAACFwA+Egf7//4P4/g+EsAAAAIP4/Q+EiQAAALgDAAAA6WX+//9FheR18UiLPbMpAABIiem+AQAAADHASI0VugkAAOh9+///69JIiwtIiz2RKQAASI0VogoAADHAvgEAAADoXvv//0iLPXcpAABIjRWoCgAAMcC+AQAAAOhE+///SIs9XSkAAEiNFb4KAAAxwL4BAAAA6Cr7//+4AwAAAOnm/f//RIng6d79//9IjT1iCQAA6Hz8//+4AQAAAOnI/f//uAIAAADpvv3//+jz+///Dx8A8w8e+jHtSYnRXkiJ4kiD5PBQVEUxwDHJSI09cfz///8VwygAAPRmLg8fhAAAAAAASI09ySgAAEiNBcIoAABIOfh0FUiLBYYoAABIhcB0Cf/gDx+AAAAAAMMPH4AAAAAASI09mSgAAEiNNZIoAABIKf5IifBIwe4/SMH4A0gBxkjR/nQUSIsFTSgAAEiFwHQI/+BmDx9EAADDDx+AAAAAAPMPHvqAPW0oAAAAdStVSIM9KigAAABIieV0DEiLPTYoAADoCfr//+hk////xgVFKAAAAV3DDx8Aww8fgAAAAADzDx766Xf///8PH4AAAAAAQVVBVEmJ/EiD7AjowAMAAEyJ574vAAAAQYnF6ID6//9IjVABSIXATA9F4kGD/f50L0WF7XR6QYP9/XRMTIniSI012AcAAL8BAAAAMcDozvn//0iDxAhEiehBXEFdw2aQTIniSI01ZggAAL8BAAAAMcDoqvn//0iDxAhEiehBXEFdw2YPH0QAAEyJ4kiNNW4IAAC/AQAAADHA6IL5//9Ig8QIRInoQVxBXcNmDx9EAABMieJIjTVKBwAAvwEAAAAxwOha+f//SIPECESJ6EFcQV3DZi4PH4QAAAAAAA8fQABBV0FWSYnWQVVJifVIjTXVCAAAQVRVU0iD7AjoQPn//0iFwA+E2AAAAEmJxLoCAAAAMfZIicfo9fj//0yJ5+jN+P//TInnSYnHSIXAD4ijAAAA6In5//9JjX8B6PD4//9IicVIhcAPhIYAAABMieFMifq+AQAAAEiJx+iR+f//TInnSInD6Lb5//9IjTVaCAAASInvxkQdAADoMvn//0iJwkgp6kiDwgFIhcBID0Xa6Lz4//9Ig+wITYnpSInpQVa6QAAAAEiJx0mJ2EiNNT4IAADo2fn//0iJ7+ix+P//WDHAWkiDxAhbXUFcQV1BXkFfw0yJ5+hG+f//uP/////r4oPI/+vdZi4PH4QAAAAAAPMPHvpBVkiNNVoGAABJif5BVUFUVVNIg+xgZEiLBCUoAAAASIlEJFgxwOgh+P//SIXAD4R/AQAASInFugIAAAAx9kiJx+jW9///SInv6K73//9Iie9IicNIhcAPiFEBAADoavj//0iNewHo0ff//0mJxEiFwA+ENAEAAL4BAAAASInpSInaSInH6HL4//9BxgQcAEiJ7+iV+P//SI01OQcAAEyJ5+gW+P//SIXAdAPGAABIjTU2BwAATIn36I/3//9IicVIhcAPhPcAAABIicZMiefoCPj//0iJ7+hQ+P//TInnTI1kJBDok/f//0iNVCQMTInmTIn36PP9//9BicWFwA+FrwAAAEiNNeIGAABMiffoOff//0iJxUiFwA+ElAAAAEiJx0iNFa8GAAC+AQAAADHA6Nf2//+LRCQMhcB0MDHbTI01qQYAAGYPH0QAAEEPtgwcTInyvgEAAABIie8xwEiDwwHopfb//zlcJAx330iJ70iNFX4GAAC+AQAAADHA6In2//9Iie/ooff//0iLRCRYZEgrBCUoAAAAdSBIg8RgRInoW11BXEFdQV7DSInv6Hn3//9Bvf/////r0OhM9///TInnQYPN/+iw9v//671mZi4PH4QAAAAAAA8fAPMPHvpBV0iNNXoEAABBVkFVSYn9QVRVU0iB7GgGAABkSIsEJSgAAABIiYQkWAYAADHA6Dn2//9IhcAPhMABAABmD+/ASYnHSI2cJFACAABJvCMgU0lHOkhNDylEJFBMjTWzBQAASL1BQy1TSEEyNQ8pRCRgDylEJHAPKYQkgAAAAA8phCSQAAAADymEJKAAAAAPKYQksAAAAA8phCTAAAAADymEJNAAAAAPKYQk4AAAAA8phCTwAAAADymEJAABAAAPKYQkEAEAAA8phCQgAQAADymEJDABAAAPKYQkQAEAAA8fgAAAAABMifq+AAQAAEiJ3+iY9f//SIXAdENIi0MISIsTSDHoTDHiSAnQddlmgXsQNjp10UiNtCRiAgAASI18JFC6AAEAAOji9f//TIn2SInH6Ef2///GRARQAOuoTIn/6Aj2//+AfCRQAA+EnwAAAEyNdCQQSI1UJAxMie9MifboqPv//4XAD4WQAAAAi0QkDDHbTI2sJFABAABMjSWOBAAATInthcB0MA8fQABFD7YEHkiJ70yJ4b4BAAAASMfC/////zHASIPDAUiDxQLouvX//zlcJAx31EiNdCRQTInv6Hf1//+FwHUsSIuUJFgGAABkSCsUJSgAAAB1J0iBxGgGAABbXUFcQV1BXkFfw7j+////69S4/f///+vNuP/////rxugk9f//8w8e+kiD7AhIg8QIwwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAIAICDinIUgJS0yMHMg562+5ZCN5pyJ5pWICgAgIOKdjCAlLTIwcyDor7vlj5blpLHotKUKAOKdjCDot6/lvoTkuI3lrZjlnKg6ICVzCgBvcGVuZGlyAPCfk4sg6aqM6K+B55uu5b2VOiAlcwoALmNzdgAlcy8lcwDwn5OLIOmqjOivgeaWh+S7tjogJXMKAOKchSDlhajpg6jpgJrov4cgKCVkLyVkKQoA4p2MICVkLyVkIOaWh+S7tumqjOivgeWksei0pQoAAAAAAAAAICDimqAgICUtMjBzIOaXoOetvuWQjSAo5pen54mI5pys55Sf5oiQKQoAAAAAAAAAICDinYwgJS0yMHMg562+5ZCN5LiN5Yy56YWNIOKAlCDmlbDmja7lj6/og73ooqvnr6HmlLkhCgDnlKjms5U6ICVzIFstcV0gPGZpbGVfb3JfZGlyPgoAACAgLXEgIOWuiemdmeaooeW8jywg5Y+q6L+U5Zue6YCA5Ye656CBOgoAAAAAAAAAACAgICAgICAwPeetvuWQjeacieaViCAgMT3nrb7lkI3ml6DmlYggIDI95peg562+5ZCNICAzPUlP6ZSZ6K+vCgByYgAKIyBTSUc6SE1BQy1TSEEyNTY6AHcAYQAlMDJ4AA0KAAAAAAAAMDEyMzQ1Njc4OWFiY2RlZjAxMjM0NTY3ODlhYmNkZWYwMTIzNDU2Nzg5YWJjZGVmMDEyMzQ1Njc4OWFiY2RlZgAAAAABGwM7UAAAAAkAAADs7f//hAAAAKzv//+sAAAAvO///8QAAABs8f//KAEAANz0//9sAAAAzPX//9wAAACs9v//jAEAALz3///kAQAAnPn//ywCAAAUAAAAAAAAAAF6UgABeBABGwwHCJABAAAUAAAAHAAAAGj0//8mAAAAAEQHEAAAAAAkAAAANAAAAGDt///AAQAAAA4QRg4YSg8LdwiAAD8aOiozJCIAAAAAFAAAAFwAAAD47v//EAAAAAAAAAAAAAAAFAAAAHQAAADw7v//sAEAAAAAAAAAAAAASAAAAIwAAADo9P//0gAAAABCDhCNAkIOGIwDRw4gAksKDhhFDhBCDghDC1oKDhhFDhBCDghHC1oKDhhFDhBCDghHC1oOGEUOEEIOCGAAAADYAAAAPPD//20DAAAARg4QjwJCDhiOA0IOII0EQg4ojAVBDjCGBkEOOIMHSg7wCQMsAQoOOEEOMEEOKEIOIEIOGEIOEEIOCEELApwO+AlCDoAKZg74CUQO8AkAAAAAAABUAAAAPAEAABj1//8GAQAAAEIOEI8CQg4YjgNFDiCNBEwOKIwFQQ4whgZBDjiDB0QOQAKdDkhIDlBgDkhDDkBECg44QQ4wQQ4oQg4gQg4YQg4QQg4IQQsARAAAAJQBAADQ9f//0gEAAABGDhCOAkwOGI0DQg4gjARBDiiGBUEOMIMGRA6QAQOJAQoOMEQOKEEOIEIOGEIOEEIOCEELAAAATAAAANwBAABo9///DAIAAABGDhCPAkkOGI4DQg4gjQRFDiiMBUEOMIYGQQ44gwdHDqANA8gBCg44QQ4wQQ4oQg4gQg4YQg4QQg4IQQsAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADwFwAAAAAAALAXAAAAAAAAAQAAAAAAAABVAQAAAAAAAAEAAAAAAAAAZAEAAAAAAAAMAAAAAAAAAAAQAAAAAAAADQAAAAAAAADcHQAAAAAAABkAAAAAAAAA2DwAAAAAAAAbAAAAAAAAAAgAAAAAAAAAGgAAAAAAAADgPAAAAAAAABwAAAAAAAAACAAAAAAAAAD1/v9vAAAAALADAAAAAAAABQAAAAAAAAAIBwAAAAAAAAYAAAAAAAAA2AMAAAAAAAAKAAAAAAAAALQBAAAAAAAACwAAAAAAAAAYAAAAAAAAABUAAAAAAAAAAAAAAAAAAAADAAAAAAAAAOg+AAAAAAAAAgAAAAAAAACIAgAAAAAAABQAAAAAAAAABwAAAAAAAAAXAAAAAAAAAFgKAAAAAAAABwAAAAAAAACACQAAAAAAAAgAAAAAAAAA2AAAAAAAAAAJAAAAAAAAABgAAAAAAAAAHgAAAAAAAAAIAAAAAAAAAPv//28AAAAAAQAACAAAAAD+//9vAAAAAAAJAAAAAAAA////bwAAAAACAAAAAAAAAPD//28AAAAAvAgAAAAAAAD5//9vAAAAAAMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADoPAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwEAAAAAAAAEAQAAAAAAAAUBAAAAAAAABgEAAAAAAAAHAQAAAAAAAAgBAAAAAAAACQEAAAAAAAAKAQAAAAAAAAsBAAAAAAAADAEAAAAAAAANAQAAAAAAAA4BAAAAAAAADwEAAAAAAAAAARAAAAAAAAEBEAAAAAAAAgEQAAAAAAADARAAAAAAAAQBEAAAAAAABQEQAAAAAAAGARAAAAAAAAcBEAAAAAAACAEQAAAAAAAJARAAAAAAAAoBEAAAAAAACwEQAAAAAAAMARAAAAAAAA0BEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIQAAAAAAAAEdDQzogKFVidW50dSAxMS40LjAtMXVidW50dTF+MjIuMDQuMykgMTEuNC4wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAEAPH/AAAAAAAAAAAAAAAAAAAAAAkAAAABAAQAjAMAAAAAAAAgAAAAAAAAABMAAAAEAPH/AAAAAAAAAAAAAAAAAAAAACAAAAACABAAABgAAAAAAADSAAAAAAAAADEAAAAEAPH/AAAAAAAAAAAAAAAAAAAAADwAAAACABAAQBcAAAAAAAAAAAAAAAAAAD4AAAACABAAcBcAAAAAAAAAAAAAAAAAAFEAAAACABAAsBcAAAAAAAAAAAAAAAAAAGcAAAABABoAKEAAAAAAAAABAAAAAAAAAHMAAAABABYA4DwAAAAAAAAAAAAAAAAAAJoAAAACABAA8BcAAAAAAAAAAAAAAAAAAKYAAAABABUA2DwAAAAAAAAAAAAAAAAAAMUAAAAEAPH/AAAAAAAAAAAAAAAAAAAAAMwAAAACABAA4BgAAAAAAAAGAQAAAAAAADEAAAAEAPH/AAAAAAAAAAAAAAAAAAAAANkAAAABABQAsCQAAAAAAAAAAAAAAAAAAAAAAAAEAPH/AAAAAAAAAAAAAAAAAAAAAOcAAAAAABMANCIAAAAAAAAAAAAAAAAAAPoAAAABABgA6D4AAAAAAAAAAAAAAAAAABABAAABABcA6DwAAAAAAAAAAAAAAAAAAC0CAAAgABkAAEAAAAAAAAAAAAAAAAAAABkBAAASAAAAAAAAAAAAAAAAAAAAAAAAADECAAASABAAEBcAAAAAAAAmAAAAAAAAACsBAAASAAAAAAAAAAAAAAAAAAAAAAAAAEUBAAAgAAAAAAAAAAAAAAAAAAAAAAAAAFQBAAASAAAAAAAAAAAAAAAAAAAAAAAAAGYBAAASAAAAAAAAAAAAAAAAAAAAAAAAAH8BAAASAhEA3B0AAAAAAAAAAAAAAAAAAIUBAAASAAAAAAAAAAAAAAAAAAAAAAAAAJgBAAASAAAAAAAAAAAAAAAAAAAAAAAAAKoBAAASAAAAAAAAAAAAAAAAAAAAAAAAAMMBAAASAAAAAAAAAAAAAAAAAAAAAAAAANUBAAAgAAAAAAAAAAAAAAAAAAAAAAAAAPEBAAARABIAACAAAAAAAAAEAAAAAAAAAAACAAASAAAAAAAAAAAAAAAAAAAAAAAAABECAAAgAAAAAAAAAAAAAAAAAAAAAAAAACsCAAAQABkAAEAAAAAAAAAAAAAAAAAAADgCAAASABAA0BsAAAAAAAAMAgAAAAAAAEQCAAASAAAAAAAAAAAAAAAAAAAAAAAAAFgCAAAiAAAAAAAAAAAAAAAAAAAAAAAAAHMCAAASAAAAAAAAAAAAAAAAAAAAAAAAAIcCAAASAAAAAAAAAAAAAAAAAAAAAAAAAJsCAAARAhkAEEAAAAAAAAAAAAAAAAAAAKcCAAASAAAAAAAAAAAAAAAAAAAAAAAAALoCAAASAAAAAAAAAAAAAAAAAAAAAAAAAM0CAAARAhkACEAAAAAAAAAAAAAAAAAAANoCAAASAAAAAAAAAAAAAAAAAAAAAAAAAOwCAAASAAAAAAAAAAAAAAAAAAAAAAAAAAUDAAASAAAAAAAAAAAAAAAAAAAAAAAAABcDAAAQABoAEEAAAAAAAAAAAAAAAAAAACMDAAASAAAAAAAAAAAAAAAAAAAAAAAAAD4DAAASAAAAAAAAAAAAAAAAAAAAAAAAAFEDAAAQABoAMEAAAAAAAAAAAAAAAAAAAFYDAAASAAAAAAAAAAAAAAAAAAAAAAAAAGkDAAASAAAAAAAAAAAAAAAAAAAAAAAAAH4DAAASAAAAAAAAAAAAAAAAAAAAAAAAAJgDAAARABoAIEAAAAAAAAAIAAAAAAAAAKsDAAASAAAAAAAAAAAAAAAAAAAAAAAAAL8DAAASAAAAAAAAAAAAAAAAAAAAAAAAANoDAAASAAAAAAAAAAAAAAAAAAAAAAAAAO0DAAAQABkAEEAAAAAAAAAAAAAAAAAAAPQDAAASAAAAAAAAAAAAAAAAAAAAAAAAABEEAAASABAA8BkAAAAAAADSAQAAAAAAABsEAAASAAAAAAAAAAAAAAAAAAAAAAAAACsEAAASAAAAAAAAAAAAAAAAAAAAAAAAAD4EAAASABAAoBMAAAAAAABtAwAAAAAAAEMEAAASAgwAABAAAAAAAAAAAAAAAAAAAABTY3J0MS5vAF9fYWJpX3RhZwBjc3ZfdmVyaWZ5LmMAdmVyaWZ5X2FuZF9wcmludABjcnRzdHVmZi5jAGRlcmVnaXN0ZXJfdG1fY2xvbmVzAF9fZG9fZ2xvYmFsX2R0b3JzX2F1eABjb21wbGV0ZWQuMABfX2RvX2dsb2JhbF9kdG9yc19hdXhfZmluaV9hcnJheV9lbnRyeQBmcmFtZV9kdW1teQBfX2ZyYW1lX2R1bW15X2luaXRfYXJyYXlfZW50cnkAc2lnbi5jAGNvbXB1dGVfaG1hYwBfX0ZSQU1FX0VORF9fAF9fR05VX0VIX0ZSQU1FX0hEUgBfR0xPQkFMX09GRlNFVF9UQUJMRV8AX0RZTkFNSUMAZnRlbGxAR0xJQkNfMi4yLjUAX19mcHJpbnRmX2Noa0BHTElCQ18yLjMuNABfX2dtb25fc3RhcnRfXwBmc2Vla0BHTElCQ18yLjIuNQBfX3ByaW50Zl9jaGtAR0xJQkNfMi4zLjQAX2ZpbmkAbWFsbG9jQEdMSUJDXzIuMi41AGZvcGVuQEdMSUJDXzIuMi41AEVWUF9zaGEyNTZAT1BFTlNTTF8zLjAuMABmZ2V0c0BHTElCQ18yLjIuNQBfSVRNX2RlcmVnaXN0ZXJUTUNsb25lVGFibGUAX0lPX3N0ZGluX3VzZWQAZnJlZUBHTElCQ18yLjIuNQBfSVRNX3JlZ2lzdGVyVE1DbG9uZVRhYmxlAF9fZGF0YV9zdGFydAB2ZXJpZnlfZmlsZQBvcGVuZGlyQEdMSUJDXzIuMi41AF9fY3hhX2ZpbmFsaXplQEdMSUJDXzIuMi41AHJlYWRkaXJAR0xJQkNfMi4yLjUAc3RycmNockBHTElCQ18yLjIuNQBfX1RNQ19FTkRfXwBzdHJzdHJAR0xJQkNfMi4yLjUAcmV3aW5kQEdMSUJDXzIuMi41AF9fZHNvX2hhbmRsZQBmcHV0c0BHTElCQ18yLjIuNQBfX3N0cmNweV9jaGtAR0xJQkNfMi4zLjQAZnJlYWRAR0xJQkNfMi4yLjUAX19ic3Nfc3RhcnQAX19zdGFja19jaGtfZmFpbEBHTElCQ18yLjQAc3RyY21wQEdMSUJDXzIuMi41AF9lbmQAZmNsb3NlQEdMSUJDXzIuMi41AGNsb3NlZGlyQEdMSUJDXzIuMi41AF9fc3ByaW50Zl9jaGtAR0xJQkNfMi4zLjQAc3RkZXJyQEdMSUJDXzIuMi41AHN0cmNzcG5AR0xJQkNfMi4yLjUAX19zbnByaW50Zl9jaGtAR0xJQkNfMi4zLjQAcGVycm9yQEdMSUJDXzIuMi41AF9lZGF0YQBfX2xpYmNfc3RhcnRfbWFpbkBHTElCQ18yLjM0AHNpZ25fZmlsZQBzdGF0QEdMSUJDXzIuMzMASE1BQ0BPUEVOU1NMXzMuMC4wAG1haW4AX2luaXQAAC5zeW10YWIALnN0cnRhYgAuc2hzdHJ0YWIALmludGVycAAubm90ZS5nbnUucHJvcGVydHkALm5vdGUuZ251LmJ1aWxkLWlkAC5ub3RlLkFCSS10YWcALmdudS5oYXNoAC5keW5zeW0ALmR5bnN0cgAuZ251LnZlcnNpb24ALmdudS52ZXJzaW9uX3IALnJlbGEuZHluAC5yZWxhLnBsdAAuaW5pdAAucGx0LmdvdAAucGx0LnNlYwAudGV4dAAuZmluaQAucm9kYXRhAC5laF9mcmFtZV9oZHIALmVoX2ZyYW1lAC5pbml0X2FycmF5AC5maW5pX2FycmF5AC5keW5hbWljAC5kYXRhAC5ic3MALmNvbW1lbnQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGwAAAAEAAAACAAAAAAAAABgDAAAAAAAAGAMAAAAAAAAcAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAACMAAAAHAAAAAgAAAAAAAAA4AwAAAAAAADgDAAAAAAAAMAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAA2AAAABwAAAAIAAAAAAAAAaAMAAAAAAABoAwAAAAAAACQAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAASQAAAAcAAAACAAAAAAAAAIwDAAAAAAAAjAMAAAAAAAAgAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAFcAAAD2//9vAgAAAAAAAACwAwAAAAAAALADAAAAAAAAKAAAAAAAAAAGAAAAAAAAAAgAAAAAAAAAAAAAAAAAAABhAAAACwAAAAIAAAAAAAAA2AMAAAAAAADYAwAAAAAAADADAAAAAAAABwAAAAEAAAAIAAAAAAAAABgAAAAAAAAAaQAAAAMAAAACAAAAAAAAAAgHAAAAAAAACAcAAAAAAAC0AQAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAHEAAAD///9vAgAAAAAAAAC8CAAAAAAAALwIAAAAAAAARAAAAAAAAAAGAAAAAAAAAAIAAAAAAAAAAgAAAAAAAAB+AAAA/v//bwIAAAAAAAAAAAkAAAAAAAAACQAAAAAAAIAAAAAAAAAABwAAAAIAAAAIAAAAAAAAAAAAAAAAAAAAjQAAAAQAAAACAAAAAAAAAIAJAAAAAAAAgAkAAAAAAADYAAAAAAAAAAYAAAAAAAAACAAAAAAAAAAYAAAAAAAAAJcAAAAEAAAAQgAAAAAAAABYCgAAAAAAAFgKAAAAAAAAiAIAAAAAAAAGAAAAGAAAAAgAAAAAAAAAGAAAAAAAAAChAAAAAQAAAAYAAAAAAAAAABAAAAAAAAAAEAAAAAAAABsAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAnAAAAAEAAAAGAAAAAAAAACAQAAAAAAAAIBAAAAAAAADAAQAAAAAAAAAAAAAAAAAAEAAAAAAAAAAQAAAAAAAAAKcAAAABAAAABgAAAAAAAADgEQAAAAAAAOARAAAAAAAAEAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAEAAAAAAAAACwAAAAAQAAAAYAAAAAAAAA8BEAAAAAAADwEQAAAAAAALABAAAAAAAAAAAAAAAAAAAQAAAAAAAAABAAAAAAAAAAuQAAAAEAAAAGAAAAAAAAAKATAAAAAAAAoBMAAAAAAAA8CgAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAL8AAAABAAAABgAAAAAAAADcHQAAAAAAANwdAAAAAAAADQAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAADFAAAAAQAAAAIAAAAAAAAAACAAAAAAAAAAIAAAAAAAADECAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAzQAAAAEAAAACAAAAAAAAADQiAAAAAAAANCIAAAAAAABUAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAANsAAAABAAAAAgAAAAAAAACIIgAAAAAAAIgiAAAAAAAALAIAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAADlAAAADgAAAAMAAAAAAAAA2DwAAAAAAADYLAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAgAAAAAAAAA8QAAAA8AAAADAAAAAAAAAOA8AAAAAAAA4CwAAAAAAAAIAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAIAAAAAAAAAP0AAAAGAAAAAwAAAAAAAADoPAAAAAAAAOgsAAAAAAAAAAIAAAAAAAAHAAAAAAAAAAgAAAAAAAAAEAAAAAAAAACrAAAAAQAAAAMAAAAAAAAA6D4AAAAAAADoLgAAAAAAABgBAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAgAAAAAAAAABgEAAAEAAAADAAAAAAAAAABAAAAAAAAAADAAAAAAAAAQAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAwBAAAIAAAAAwAAAAAAAAAgQAAAAAAAABAwAAAAAAAAEAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAARAQAAAQAAADAAAAAAAAAAAAAAAAAAAAAQMAAAAAAAAC0AAAAAAAAAAAAAAAAAAAABAAAAAAAAAAEAAAAAAAAAAQAAAAIAAAAAAAAAAAAAAAAAAAAAAAAAQDAAAAAAAABgBgAAAAAAAB0AAAAVAAAACAAAAAAAAAAYAAAAAAAAAAkAAAADAAAAAAAAAAAAAAAAAAAAAAAAAKA2AAAAAAAASQQAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAARAAAAAwAAAAAAAAAAAAAAAAAAAAAAAADpOgAAAAAAABoBAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAA"""

def _get_csv_verify():
    cache = '/tmp/.tbox_csv_verify_cached'
    try:
        b64 = _CSV_B64.strip()
        if len(b64) < 100: raise ValueError('not embedded')
        binary = base64.b64decode(b64)
        if os.path.exists(cache) and os.path.getsize(cache) == len(binary):
            return cache
        with open(cache, 'wb') as f: f.write(binary)
        os.chmod(cache, 0o755)
        return cache
    except:
        return os.path.join(os.path.dirname(os.path.abspath(__file__)),
                            '..', 'src', 'build', 'csv_verify')
CSV_VERIFY_BIN = _get_csv_verify()

EXPECTED_VERSION = "26.0.1"

def check_csv_version(profile_dir):
    """读取所有 CSV 的 # VERSION: 行, 逐文件比对期望版本。返回 None=全部一致, str=警告"""
    try:
        mismatched = []
        no_ver = []
        for fn in sorted(os.listdir(profile_dir)):
            if not fn.endswith('.csv'):
                continue
            path = os.path.join(profile_dir, fn)
            with open(path) as f:
                for line in f:
                    if line.startswith('# VERSION:'):
                        ver = line.split(':')[1].strip()
                        if ver != EXPECTED_VERSION:
                            mismatched.append((fn, ver))
                        break
                else:
                    no_ver.append(fn)
        if mismatched:
            detail = ', '.join(f'{f}(v{ver})' for f, ver in mismatched[:3])
            if len(mismatched) > 3:
                detail += f' ... 等{len(mismatched)}个文件'
            return f"版本不匹配 ({detail} — 绘图 v{EXPECTED_VERSION})"
        if no_ver:
            detail = ', '.join(no_ver[:3])
            if len(no_ver) > 3:
                detail += f' ... 等{len(no_ver)}个文件'
            return f"缺少版本号 (旧格式: {detail})"
    except Exception:
        pass
    return None

def verify_csv_signature(path):
    try:
        r = subprocess.run([CSV_VERIFY_BIN, '-q', path], capture_output=True, timeout=5)
        if r.returncode == 0:   return True, None
        elif r.returncode == 2: return None, None
        else:                   return False, r.stderr.decode().strip() or "签名验证失败"
    except FileNotFoundError: return 'no_binary', None
    except Exception as e:    return None, str(e)

def read_csv(path):
    rows = []
    with open(path, 'r') as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith('#'): continue
            parts = line.split(',')
            try: rows.append(float(parts[1]) if len(parts)>1 else float(parts[0]))
            except (ValueError, IndexError): pass
    return rows

def read_csv_multi(path):
    """读取多列 CSV, 返回列列表的列表 [[col0,...], [col1,...], ...]"""
    cols = []
    with open(path, 'r') as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith('#'): continue
            parts = line.split(',')
            if parts[0] == 'sample' or parts[0] == 'sec':
                cols = [[] for _ in range(len(parts)-1)]
                continue
            try:
                for c in range(1, len(parts)):
                    cols[c-1].append(float(parts[c]))
            except (ValueError, IndexError): pass
    return cols

PALETTE = ['#58a6ff','#3fb950','#f0883e','#d2a8ff','#f85149','#f59e0b',
           '#79c0ff','#56d364','#e29b44','#bc8cff','#ff7b72','#f2cc60']

def svg_line_chart_multi(series_list, width, height, ylabel, labels=None, sig_ok=None):
    """多系列折线图 SVG — 每个核心一条线"""
    if not series_list or not series_list[0]:
        return f'<svg viewBox="0 0 {width} {height}" xmlns="http://www.w3.org/2000/svg"><rect x="0" y="0" width="{width}" height="{height}" fill="#161b22" rx="4"/><text x="{width//2}" y="{height//2}" text-anchor="middle" fill="#888">No data</text></svg>'

    all_y = [y for s in series_list for y in s]
    ymax = max(all_y) if all_y else 1
    if ymax <= 10:   ymax = int(ymax) + 1
    elif ymax <= 100: ymax = ((int(ymax)//10)+1)*10
    else:             ymax = ((int(ymax)//100)+1)*100
    if ymax == 0: ymax = 1

    ml, mr, mt, mb = 52, 20, 26, 32
    pw = width - ml - mr; ph = height - mt - mb
    def ty(y): return height - mb - (y / ymax) * ph

    n_labels = labels if labels else [f'Core {i}' for i in range(len(series_list))]

    # 网格 + Y 轴
    grid = ''.join(f'<line x1="{ml}" y1="{mt+ph*i/4:.1f}" x2="{width-mr}" y2="{mt+ph*i/4:.1f}" stroke="#333" stroke-dasharray="4,4"/>' for i in range(5))
    ylbl = ''.join(f'<text x="{ml-6}" y="{mt+ph*(4-i)/4+4:.1f}" text-anchor="end" fill="#888" font-size="10">{ymax*i/4:.0f}</text>' for i in range(5))

    # 每条线
    lines = ''
    for si, series in enumerate(series_list):
        if len(series) < 2: continue
        color = PALETTE[si % len(PALETTE)]
        n = len(series); gap = pw / max(1, n-1)
        pts = ' '.join(f'{ml+i*gap:.1f},{ty(y):.1f}' for i, y in enumerate(series))
        lines += f'<polyline points="{pts}" fill="none" stroke="{color}" stroke-width="2" stroke-linejoin="round"/>'

    # X labels
    n = len(series_list[0]); step = max(1, n//8)
    xlbl = ''.join(f'<text x="{ml+i*pw/max(1,n-1):.1f}" y="{height-mb+16}" text-anchor="middle" fill="#888" font-size="9">{i+1}</text>' for i in range(0, n, step))

    # Legend
    n_lbl = len(series_list)
    legend_bg = f'<rect x="{width-mr-62}" y="{mt-4}" width="62" height="{14*n_lbl+12}" fill="#161b22" rx="3"/>'
    legend = ''.join(f'<line x1="{width-mr-40}" y1="{mt+4+si*14+5}" x2="{width-mr-26}" y2="{mt+4+si*14+5}" stroke="{PALETTE[si%len(PALETTE)]}" stroke-width="2"/><text x="{width-mr-22}" y="{mt+4+si*14+5}" fill="#888" font-size="8">{n_labels[si]}</text>' for si in range(len(series_list)))

    sw = ''
    if sig_ok is False:
        sw = f'<rect x="0" y="0" width="{width}" height="22" fill="#f8514933" rx="0"/><text x="{width//2}" y="15" text-anchor="middle" fill="#f85149" font-size="11" font-weight="bold">⚠ 签名无效 — 数据可能被篡改</text>'
    elif sig_ok is None:
        sw = f'<rect x="0" y="0" width="{width}" height="22" fill="#d2991d33" rx="0"/><text x="{width//2}" y="15" text-anchor="middle" fill="#d2991d" font-size="11" font-weight="bold">⚠ 无签名 — 无法核实真伪</text>'
    elif sig_ok == 'no_binary':
        sw = f'<rect x="0" y="0" width="{width}" height="22" fill="#d2991d33" rx="0"/><text x="{width//2}" y="15" text-anchor="middle" fill="#d2991d" font-size="11" font-weight="bold">⚠ 无法验签 — 验签工具未找到</text>'
    title_y = 36 if sw else 14
    return f'<svg viewBox="0 0 {width} {height}" xmlns="http://www.w3.org/2000/svg"><rect x="0" y="0" width="{width}" height="{height}" fill="#161b22" rx="4"/>{sw}<text x="{width//2}" y="{title_y}" text-anchor="middle" fill="#ccc" font-size="13" font-weight="bold">{ylabel}</text>{grid}{ylbl}{xlbl}<line x1="{ml}" y1="{height-mb}" x2="{width-mr}" y2="{height-mb}" stroke="#555" stroke-width="1"/><line x1="{ml}" y1="{mt}" x2="{ml}" y2="{height-mb}" stroke="#555" stroke-width="1"/>{lines}{legend_bg}{legend}</svg>'


def svg_bar_chart(data, width, height, color, ylabel, sig_ok=None):
    if not data:
        return f'<svg viewBox="0 0 {width} {height}" xmlns="http://www.w3.org/2000/svg"><rect x="0" y="0" width="{width}" height="{height}" fill="#161b22" rx="4"/><text x="{width//2}" y="{height//2}" text-anchor="middle" fill="#888">No data</text></svg>'
    ys = data
    ymax = max(ys); ymax = int(ymax)+1 if ymax<=10 else ((int(ymax)//10)+1)*10 if ymax<=100 else ((int(ymax)//100)+1)*100
    if ymax == 0: ymax = 1
    ml, mr, mt, mb = 52, 20, 38, 40
    pw = width - ml - mr; ph = height - mt - mb
    def ty(y): return height - mb - (y / ymax) * ph
    n = len(data); gap = pw / n; bar_w = max(2, gap / 1.5)
    bars = ''.join(f'<rect x="{ml+gap*i+(gap-bar_w)/2:.1f}" y="{ty(y):.1f}" width="{bar_w:.1f}" height="{max(1,ty(0)-ty(y)):.1f}" fill="{color}" opacity="0.8" rx="2"/>' for i,y in enumerate(ys))
    grid = ''.join(f'<line x1="{ml}" y1="{mt+ph*i/4:.1f}" x2="{width-mr}" y2="{mt+ph*i/4:.1f}" stroke="#333" stroke-dasharray="4,4"/>' for i in range(5))
    ylbl = ''.join(f'<text x="{ml-6}" y="{mt+ph*(4-i)/4+4:.1f}" text-anchor="end" fill="#888" font-size="10">{ymax*i/4:.0f}</text>' for i in range(5))
    xlbl = ''; step = max(1, n//8)
    for i in range(0, n, step):
        xlbl += f'<text x="{ml+gap*i+gap/2:.1f}" y="{height-mb+16}" text-anchor="middle" fill="#888" font-size="9">{i+1}</text>'
    warning = ''; title_y = 16
    if sig_ok is False:
        warning = f'<rect x="0" y="0" width="{width}" height="22" fill="#f8514933" rx="0"/><text x="{width//2}" y="15" text-anchor="middle" fill="#f85149" font-size="11" font-weight="bold">⚠ 签名无效 — 数据可能被篡改</text>'
        title_y = 36
    elif sig_ok is None:
        warning = f'<rect x="0" y="0" width="{width}" height="22" fill="#d2991d33" rx="0"/><text x="{width//2}" y="15" text-anchor="middle" fill="#d2991d" font-size="11" font-weight="bold">⚠ 无签名 — 无法核实真伪</text>'
        title_y = 36
    elif sig_ok == 'no_binary':
        warning = f'<rect x="0" y="0" width="{width}" height="22" fill="#d2991d33" rx="0"/><text x="{width//2}" y="15" text-anchor="middle" fill="#d2991d" font-size="11" font-weight="bold">⚠ 无法验签 — 验签工具未找到</text>'
        title_y = 36
    return f'<svg viewBox="0 0 {width} {height}" xmlns="http://www.w3.org/2000/svg"><rect x="0" y="0" width="{width}" height="{height}" fill="#161b22" rx="4"/><text x="{width//2}" y="{title_y}" text-anchor="middle" fill="#ccc" font-size="13" font-weight="bold">{ylabel}</text>{warning}{grid}{ylbl}{xlbl}<line x1="{ml}" y1="{height-mb}" x2="{width-mr}" y2="{height-mb}" stroke="#555" stroke-width="1"/><line x1="{ml}" y1="{mt}" x2="{ml}" y2="{height-mb}" stroke="#555" stroke-width="1"/>{bars}</svg>'

def build_html(profile_dir):
    proc_name = "unknown"
    rpt = os.path.join(profile_dir, "report.txt")
    if os.path.exists(rpt):
        for line in open(rpt):
            if "进程名称:" in line: proc_name = line.split(":")[-1].strip(); break
    csv_files = {'cpu':'cpu.csv','mem':'mem.csv','threads_fd':'threads_fd.csv','io':'io.csv','core':'core.csv','net':'net.csv'}
    sig = {}
    for k, fn in csv_files.items():
        fp = os.path.join(profile_dir, fn)
        sig[k] = verify_csv_signature(fp) if os.path.exists(fp) else (None, None)
    cpu_raw = read_csv(os.path.join(profile_dir,"cpu.csv"))
    mem_cols = read_csv_multi(os.path.join(profile_dir,"mem.csv"))
    mem_rss = mem_cols[0] if mem_cols else []
    mem_pss = mem_cols[1] if len(mem_cols) > 1 else []
    mem_uss = mem_cols[2] if len(mem_cols) > 2 else []
    thr_cols = read_csv_multi(os.path.join(profile_dir,"threads_fd.csv"))
    tr  = thr_cols[0] if thr_cols else []
    fd  = thr_cols[1] if len(thr_cols) > 1 else []
    io_cols = read_csv_multi(os.path.join(profile_dir,"io.csv"))
    ior = io_cols[0] if io_cols else []
    iow = io_cols[1] if len(io_cols) > 1 else []
    # core.csv: variable columns, read all
    core_cols = []
    core_path = os.path.join(profile_dir, "core.csv")
    if os.path.exists(core_path):
        core_data = read_csv_multi(core_path) if os.path.exists(core_path) else []
    w, h = 500, 260
    sf = lambda k: sig[k][0] if sig.get(k) else None
    # Per-core CPU chart (show all cores as average, or first core if only 1)
    core_chart = ''
    if core_data and len(core_data) > 0:
        n = len(core_data)
        label = 'Per-Core CPU (%)'
        if core_data:
            all_max = max(max(s) for s in core_data)
            label += f' — max: {all_max:.1f}'
        core_labels = [f'Core {i}' for i in range(n)]
        core_chart = svg_line_chart_multi(core_data, w, h, label, labels=core_labels, sig_ok=sf('core'))

    def label_with_max(data, base):
        return f'{base} — max: {max(data):.1f}' if data else base

    charts = [
        ('CPU (%)', svg_bar_chart(cpu_raw,w,h,'#58a6ff',label_with_max(cpu_raw,'CPU Usage (%)'),sig_ok=sf('cpu'))),
        ('Threads', svg_bar_chart(tr,w,h,'#f0883e',label_with_max(tr,'Thread Count'),sig_ok=sf('threads_fd'))),
        ('File Descriptors', svg_bar_chart(fd,w,h,'#d2a8ff',label_with_max(fd,'Open File Descriptors'),sig_ok=sf('threads_fd'))),
    ]
    panels = ''.join(f'<div class="chart-panel">{s}</div>' for _, s in charts)

    # Memory line chart (RSS + PSS + USS)
    if mem_rss and mem_pss and mem_uss:
        mx = lambda d: f'{max(d):.0f}' if d else '0'
        mem_label = f'Memory (KB) — max RSS:{mx(mem_rss)} PSS:{mx(mem_pss)} USS:{mx(mem_uss)}'
        mem_chart = svg_line_chart_multi([mem_rss, mem_pss, mem_uss], w, h,
                                          mem_label, labels=['RSS','PSS','USS'], sig_ok=sf('mem'))
        panels += f'<div class="chart-panel">{mem_chart}</div>'

    # IO line chart (Read + Write)
    if ior and iow:
        mx = lambda d: f'{max(d):.0f}' if d else '0'
        io_label = f'IO Throughput (KB/s) — max R:{mx(ior)} W:{mx(iow)}'
        io_chart = svg_line_chart_multi([ior, iow], w, h, io_label, labels=['Read','Write'], sig_ok=sf('io'))
        panels += f'<div class="chart-panel">{io_chart}</div>'

    # Network line chart
    net_path = os.path.join(profile_dir, 'net.csv')
    if os.path.exists(net_path):
        net_cols = read_csv_multi(net_path)
        if net_cols:
            with open(net_path) as f:
                hdr = f.readline().strip().split(',')
            all_ifaces = [(i, hdr[i+1]) for i in range(0, len(hdr)-1, 2)]
            if all_ifaces:
                net_series = [net_cols[i] for i, _ in all_ifaces]
                net_labels = [n for _, n in all_ifaces]
                all_max = max(max(s) for s in net_series) if net_series else 0
                net_chart = svg_line_chart_multi(net_series, w, h,
                                                  f'Network (KB/s) — max: {all_max:.0f}',
                                                  labels=net_labels, sig_ok=sf('net'))
                panels += f'<div class="chart-panel">{net_chart}</div>'

    if core_chart:
        panels += f'<div class="chart-panel">{core_chart}</div>'
    return f'<!DOCTYPE html><html lang="zh-CN"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1.0"><title>TBox Resource Profile v26.0.1 — {proc_name}</title><style>*{{box-sizing:border-box;margin:0;padding:0}}body{{background:#0d1117;color:#c9d1d9;font-family:-apple-system,BlinkMacSystemFont,"Microsoft YaHei",sans-serif;padding:24px 32px}}h1{{color:#f0f6fc;font-size:1.4rem;margin-bottom:4px}}.sub{{color:#8b949e;font-size:.85rem;margin-bottom:24px}}.grid{{display:grid;grid-template-columns:repeat(auto-fill,minmax(520px,1fr));gap:18px}}.chart-panel{{background:#161b22;border:1px solid #30363d;border-radius:8px;padding:12px}}.chart-panel svg{{width:100%;height:auto;display:block}}.footer{{text-align:center;color:#8b949e;font-size:.75rem;margin-top:30px;padding-top:16px;border-top:1px solid #30363d}}</style></head><body><h1>TBox Resource Profile v26.0.1 — {proc_name}</h1><p class="sub">Data source: {profile_dir}</p><div class="grid">{panels}</div><div class="footer"><p>Generated by plot_profile.py — TBox Resource Monitor Toolkit</p></div></body></html>'

if __name__ == '__main__':
    if len(sys.argv) == 2 and sys.argv[1] in ('-v', '--version'): print('plot_profile.py v26.0.1'); sys.exit(0)
    if len(sys.argv) < 2: print(f"用法: {sys.argv[0]} <profile_dir>"); sys.exit(1)
    d = sys.argv[1]
    if not os.path.isdir(d): print(f"❌ 目录不存在: {d}"); sys.exit(1)
    out = os.path.join(d, "chart.html")
    ver_warn = check_csv_version(d)
    html = build_html(d)
    if ver_warn:
        html = html.replace('<h1>', f'<p style="color:#f59e0b;font-size:12px;margin-bottom:8px">⚠ {ver_warn}</p>\n<h1>')
    open(out, 'w', encoding='utf-8').write(html)
    print(f"✅ 图表已生成: {out}")
