#!/usr/bin/env python3
"""
plot_gui.py — TBox 应用资源画像本地 GUI 客户端 (内嵌 csv_verify)

用法: python3 plot_gui.py <profile_dir>
"""
import sys, os, csv, subprocess, base64
import tkinter as tk
from tkinter import ttk

# ── 内嵌 csv_verify 二进制 (base64) ────────────────
_CSV_B64 = """f0VMRgIBAQAAAAAAAAAAAAMAPgABAAAAEBcAAAAAAABAAAAAAAAAAAg8AAAAAAAAAAAAAEAAOAANAEAAHwAeAAYAAAAEAAAAQAAAAAAAAABAAAAAAAAAAEAAAAAAAAAA2AIAAAAAAADYAgAAAAAAAAgAAAAAAAAAAwAAAAQAAAAYAwAAAAAAABgDAAAAAAAAGAMAAAAAAAAcAAAAAAAAABwAAAAAAAAAAQAAAAAAAAABAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOAMAAAAAAAA4AwAAAAAAAAAEAAAAAAAAAEAAAAFAAAAABAAAAAAAAAAEAAAAAAAAAAQAAAAAAAA6Q0AAAAAAADpDQAAAAAAAAAQAAAAAAAAAQAAAAQAAAAAIAAAAAAAAAAgAAAAAAAAACAAAAAAAAC0BAAAAAAAALQEAAAAAAAAABAAAAAAAAABAAAABgAAANgsAAAAAAAA2DwAAAAAAADYPAAAAAAAADgDAAAAAAAAWAMAAAAAAAAAEAAAAAAAAAIAAAAGAAAA6CwAAAAAAADoPAAAAAAAAOg8AAAAAAAAAAIAAAAAAAAAAgAAAAAAAAgAAAAAAAAABAAAAAQAAAA4AwAAAAAAADgDAAAAAAAAOAMAAAAAAAAwAAAAAAAAADAAAAAAAAAACAAAAAAAAAAEAAAABAAAAGgDAAAAAAAAaAMAAAAAAABoAwAAAAAAAEQAAAAAAAAARAAAAAAAAAAEAAAAAAAAAFPldGQEAAAAOAMAAAAAAAA4AwAAAAAAADgDAAAAAAAAMAAAAAAAAAAwAAAAAAAAAAgAAAAAAAAAUOV0ZAQAAAA0IgAAAAAAADQiAAAAAAAANCIAAAAAAABUAAAAAAAAAFQAAAAAAAAABAAAAAAAAABR5XRkBgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAFLldGQEAAAA2CwAAAAAAADYPAAAAAAAANg8AAAAAAAAKAMAAAAAAAAoAwAAAAAAAAEAAAAAAAAAL2xpYjY0L2xkLWxpbnV4LXg4Ni02NC5zby4yAAAAAAAEAAAAIAAAAAUAAABHTlUAAgAAwAQAAAADAAAAAAAAAAKAAMAEAAAAAQAAAAAAAAAEAAAAFAAAAAMAAABHTlUA7JPq5Gd/o6eycAdyDPKITTKEvLUEAAAAEAAAAAEAAABHTlUAAAAAAAMAAAACAAAAAAAAAAAAAAACAAAAIAAAAAEAAAAGAAAAAAGBAAAAAAIgAAAAIQAAANFlzm058oscAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA5AAAABIAAAAAAAAAAAAAAAAAAAAAAAAApAAAABIAAAAAAAAAAAAAAAAAAAAAAAAAAQAAACAAAAAAAAAAAAAAAAAAAAAAAAAAfwAAABIAAAAAAAAAAAAAAAAAAAAAAAAAawAAABIAAAAAAAAAAAAAAAAAAAAAAAAAeAAAABIAAAAAAAAAAAAAAAAAAAAAAAAAvwAAABIAAAAAAAAAAAAAAAAAAAAAAAAARgAAABIAAAAAAAAAAAAAAAAAAAAAAAAAZQAAABIAAAAAAAAAAAAAAAAAAAAAAAAAEAAAACAAAAAAAAAAAAAAAAAAAAAAAAAA6gAAABIAAAAAAAAAAAAAAAAAAAAAAAAALAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAIAEAABIAAAAAAAAAAAAAAAAAAAAAAAAAPAEAABIAAAAAAAAAAAAAAAAAAAAAAAAAGAEAABIAAAAAAAAAAAAAAAAAAAAAAAAA7wAAABIAAAAAAAAAAAAAAAAAAAAAAAAANQEAABIAAAAAAAAAAAAAAAAAAAAAAAAAuQAAABIAAAAAAAAAAAAAAAAAAAAAAAAA9gAAABIAAAAAAAAAAAAAAAAAAAAAAAAAKAEAABIAAAAAAAAAAAAAAAAAAAAAAAAARAEAABIAAAAAAAAAAAAAAAAAAAAAAAAAsgAAABIAAAAAAAAAAAAAAAAAAAAAAAAAxQAAABIAAAAAAAAAAAAAAAAAAAAAAAAA2wAAABIAAAAAAAAAAAAAAAAAAAAAAAAAAwEAABIAAAAAAAAAAAAAAAAAAAAAAAAAhQAAABIAAAAAAAAAAAAAAAAAAAAAAAAAzAAAABIAAAAAAAAAAAAAAAAAAAAAAAAALgEAABIAAAAAAAAAAAAAAAAAAAAAAAAAkgAAABIAAAAAAAAAAAAAAAAAAAAAAAAAjQAAABIAAAAAAAAAAAAAAAAAAAAAAAAAUQAAABIAAAAAAAAAAAAAAAAAAAAAAAAAVgAAACIAAAAAAAAAAAAAAAAAAAAAAAAAEQEAABEAGgAgQAAAAAAAAAgAAAAAAAAAAF9fZ21vbl9zdGFydF9fAF9JVE1fZGVyZWdpc3RlclRNQ2xvbmVUYWJsZQBfSVRNX3JlZ2lzdGVyVE1DbG9uZVRhYmxlAEVWUF9zaGEyNTYASE1BQwBfX2N4YV9maW5hbGl6ZQBmZ2V0cwBfX3ByaW50Zl9jaGsAbWFsbG9jAGZzZWVrAHN0cmNzcG4Ac3RhdABfX2xpYmNfc3RhcnRfbWFpbgBfX2ZwcmludGZfY2hrAHN0cmNtcABmcHV0cwBmb3BlbgBmY2xvc2UAX19zbnByaW50Zl9jaGsAY2xvc2VkaXIAZnRlbGwAZnJlZQBzdHJzdHIAX19zdHJjcHlfY2hrAF9fc3ByaW50Zl9jaGsAc3RkZXJyAHN0cnJjaHIAb3BlbmRpcgBmcmVhZABwZXJyb3IAcmV3aW5kAHJlYWRkaXIAX19zdGFja19jaGtfZmFpbABsaWJjcnlwdG8uc28uMwBsaWJjLnNvLjYAT1BFTlNTTF8zLjAuMABHTElCQ18yLjMzAEdMSUJDXzIuMzQAR0xJQkNfMi40AEdMSUJDXzIuMy40AEdMSUJDXzIuMi41AAAAAgADAAEAAgADAAIAAgAEAAIAAQACAAEAAgACAAIAAgACAAIAAwACAAUAAgACAAIAAwACAAMAAgAGAAcABAACAAIAAQABAFUBAAAQAAAAIAAAACArcAYAAAQAbgEAAAAAAAABAAUAZAEAABAAAAAAAAAAs5GWBgAABwB8AQAAEAAAALSRlgYAAAYAhwEAABAAAAAUaWkNAAAFAJIBAAAQAAAAdBlpCQAAAwCcAQAAEAAAAHUaaQkAAAIAqAEAAAAAAADYPAAAAAAAAAgAAAAAAAAA8BcAAAAAAADgPAAAAAAAAAgAAAAAAAAAsBcAAAAAAAAIQAAAAAAAAAgAAAAAAAAACEAAAAAAAADYPwAAAAAAAAYAAAADAAAAAAAAAAAAAADgPwAAAAAAAAYAAAAKAAAAAAAAAAAAAADoPwAAAAAAAAYAAAAMAAAAAAAAAAAAAADwPwAAAAAAAAYAAAAgAAAAAAAAAAAAAAD4PwAAAAAAAAYAAAAdAAAAAAAAAAAAAAAgQAAAAAAAAAUAAAAhAAAAAAAAAAAAAAAAPwAAAAAAAAcAAAABAAAAAAAAAAAAAAAIPwAAAAAAAAcAAAACAAAAAAAAAAAAAAAQPwAAAAAAAAcAAAAEAAAAAAAAAAAAAAAYPwAAAAAAAAcAAAAFAAAAAAAAAAAAAAAgPwAAAAAAAAcAAAAGAAAAAAAAAAAAAAAoPwAAAAAAAAcAAAAHAAAAAAAAAAAAAAAwPwAAAAAAAAcAAAAIAAAAAAAAAAAAAAA4PwAAAAAAAAcAAAAJAAAAAAAAAAAAAABAPwAAAAAAAAcAAAALAAAAAAAAAAAAAABIPwAAAAAAAAcAAAANAAAAAAAAAAAAAABQPwAAAAAAAAcAAAAOAAAAAAAAAAAAAABYPwAAAAAAAAcAAAAPAAAAAAAAAAAAAABgPwAAAAAAAAcAAAAQAAAAAAAAAAAAAABoPwAAAAAAAAcAAAARAAAAAAAAAAAAAABwPwAAAAAAAAcAAAASAAAAAAAAAAAAAAB4PwAAAAAAAAcAAAATAAAAAAAAAAAAAACAPwAAAAAAAAcAAAAUAAAAAAAAAAAAAACIPwAAAAAAAAcAAAAVAAAAAAAAAAAAAACQPwAAAAAAAAcAAAAWAAAAAAAAAAAAAACYPwAAAAAAAAcAAAAXAAAAAAAAAAAAAACgPwAAAAAAAAcAAAAYAAAAAAAAAAAAAACoPwAAAAAAAAcAAAAZAAAAAAAAAAAAAACwPwAAAAAAAAcAAAAaAAAAAAAAAAAAAAC4PwAAAAAAAAcAAAAbAAAAAAAAAAAAAADAPwAAAAAAAAcAAAAcAAAAAAAAAAAAAADIPwAAAAAAAAcAAAAeAAAAAAAAAAAAAADQPwAAAAAAAAcAAAAfAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPMPHvpIg+wISIsFyS8AAEiFwHQC/9BIg8QIwwAAAAAA/zXKLgAA8v8lyy4AAA8fAPMPHvpoAAAAAPLp4f///5DzDx76aAEAAADy6dH///+Q8w8e+mgCAAAA8unB////kPMPHvpoAwAAAPLpsf///5DzDx76aAQAAADy6aH///+Q8w8e+mgFAAAA8umR////kPMPHvpoBgAAAPLpgf///5DzDx76aAcAAADy6XH///+Q8w8e+mgIAAAA8ulh////kPMPHvpoCQAAAPLpUf///5DzDx76aAoAAADy6UH///+Q8w8e+mgLAAAA8ukx////kPMPHvpoDAAAAPLpIf///5DzDx76aA0AAADy6RH///+Q8w8e+mgOAAAA8ukB////kPMPHvpoDwAAAPLp8f7//5DzDx76aBAAAADy6eH+//+Q8w8e+mgRAAAA8unR/v//kPMPHvpoEgAAAPLpwf7//5DzDx76aBMAAADy6bH+//+Q8w8e+mgUAAAA8umh/v//kPMPHvpoFQAAAPLpkf7//5DzDx76aBYAAADy6YH+//+Q8w8e+mgXAAAA8ulx/v//kPMPHvpoGAAAAPLpYf7//5DzDx76aBkAAADy6VH+//+Q8w8e+mgaAAAA8ulB/v//kPMPHvry/yUFLgAADx9EAADzDx768v8lBS0AAA8fRAAA8w8e+vL/Jf0sAAAPH0QAAPMPHvry/yX1LAAADx9EAADzDx768v8l7SwAAA8fRAAA8w8e+vL/JeUsAAAPH0QAAPMPHvry/yXdLAAADx9EAADzDx768v8l1SwAAA8fRAAA8w8e+vL/Jc0sAAAPH0QAAPMPHvry/yXFLAAADx9EAADzDx768v8lvSwAAA8fRAAA8w8e+vL/JbUsAAAPH0QAAPMPHvry/yWtLAAADx9EAADzDx768v8lpSwAAA8fRAAA8w8e+vL/JZ0sAAAPH0QAAPMPHvry/yWVLAAADx9EAADzDx768v8ljSwAAA8fRAAA8w8e+vL/JYUsAAAPH0QAAPMPHvry/yV9LAAADx9EAADzDx768v8ldSwAAA8fRAAA8w8e+vL/JW0sAAAPH0QAAPMPHvry/yVlLAAADx9EAADzDx768v8lXSwAAA8fRAAA8w8e+vL/JVUsAAAPH0QAAPMPHvry/yVNLAAADx9EAADzDx768v8lRSwAAA8fRAAA8w8e+vL/JT0sAAAPH0QAAPMPHvry/yU1LAAADx9EAADzDx76QVdBVkFVQVRVU0iJ80iB7LgEAABkSIsEJSgAAABIiYQkqAQAADHAg/8BD46xAgAAjVf+SI1GCDHtRTHkSI1M1hDrJGYPH4QAAAAAAIB6AXF1HYB6AgB1F0iDwAhBvAEAAABIOcF0FEiLEIA6LXTdSIPACEiJ1Ug5wXXsSIXtD4RdAgAASI10JBBIie/oS////4XAD4UkAgAAi0QkKCUA8AAARYXkD4WgAAAASItTCD0AQAAAD4SgAAAASI01FgwAAL8BAAAAMcDor/3//0iLewjohgMAAIPAAoPg/Q+EdQEAAEiNNVwNAAC/AQAAADHAQb0BAAAA6IH9//9BvAEAAABEielEieJIjTX6CwAAMcC/AQAAAOhi/f//McBFheQPn8BIi5QkqAQAAGRIKxQlKAAAAA+FKwIAAEiBxLgEAABbXUFcQV1BXkFfwz0AQAAAD4U7AQAASItTCEiJ1+h6/f//SInFSIXAD4TWAQAASItTCEiNNTwLAAAxwEUx7b8BAAAARTHkTI01PwsAAOjq/P//Zi4PH4QAAAAAAEiJ7+hI/f//SIXAD4SFAAAATI14E74uAAAATIn/6D79//9IicdIhcB01kyJ9uie/f//hcB1ykyLSwi5AAQAAEiNvCSgAAAASIPsCEFXugEAAAC+AAQAAEyNBdcKAABIiXwkGOi4/f//SIt8JBjoTgIAAFpIie9Zg8ACg+D9g/gBQYPc/0GDxQHow/z//0iFwA+Fe////0iJ7+hS/f//McC/AQAAAEiNNf0LAADoL/z//0WF5HQe6ar+//9IjTXnCwAAvwEAAAAxwEG9AQAAAOgM/P//RInpRInqSI01cQoAADHAvwEAAABFMeTo8Pv//+mJ/v//SInv6JMFAACFwA+Egf7//4P4/g+EsAAAAIP4/Q+EiQAAALgDAAAA6WX+//9FheR18UiLPbMpAABIiem+AQAAADHASI0VugkAAOh9+///69JIiwtIiz2RKQAASI0VogoAADHAvgEAAADoXvv//0iLPXcpAABIjRWoCgAAMcC+AQAAAOhE+///SIs9XSkAAEiNFb4KAAAxwL4BAAAA6Cr7//+4AwAAAOnm/f//RIng6d79//9IjT1iCQAA6Hz8//+4AQAAAOnI/f//uAIAAADpvv3//+jz+///Dx8A8w8e+jHtSYnRXkiJ4kiD5PBQVEUxwDHJSI09cfz///8VwygAAPRmLg8fhAAAAAAASI09ySgAAEiNBcIoAABIOfh0FUiLBYYoAABIhcB0Cf/gDx+AAAAAAMMPH4AAAAAASI09mSgAAEiNNZIoAABIKf5IifBIwe4/SMH4A0gBxkjR/nQUSIsFTSgAAEiFwHQI/+BmDx9EAADDDx+AAAAAAPMPHvqAPW0oAAAAdStVSIM9KigAAABIieV0DEiLPTYoAADoCfr//+hk////xgVFKAAAAV3DDx8Aww8fgAAAAADzDx766Xf///8PH4AAAAAAQVVBVEmJ/EiD7AjowAMAAEyJ574vAAAAQYnF6ID6//9IjVABSIXATA9F4kGD/f50L0WF7XR6QYP9/XRMTIniSI012AcAAL8BAAAAMcDozvn//0iDxAhEiehBXEFdw2aQTIniSI01ZggAAL8BAAAAMcDoqvn//0iDxAhEiehBXEFdw2YPH0QAAEyJ4kiNNW4IAAC/AQAAADHA6IL5//9Ig8QIRInoQVxBXcNmDx9EAABMieJIjTVKBwAAvwEAAAAxwOha+f//SIPECESJ6EFcQV3DZi4PH4QAAAAAAA8fQABBV0FWSYnWQVVJifVIjTXVCAAAQVRVU0iD7AjoQPn//0iFwA+E2AAAAEmJxLoCAAAAMfZIicfo9fj//0yJ5+jN+P//TInnSYnHSIXAD4ijAAAA6In5//9JjX8B6PD4//9IicVIhcAPhIYAAABMieFMifq+AQAAAEiJx+iR+f//TInnSInD6Lb5//9IjTVaCAAASInvxkQdAADoMvn//0iJwkgp6kiDwgFIhcBID0Xa6Lz4//9Ig+wITYnpSInpQVa6QAAAAEiJx0mJ2EiNNT4IAADo2fn//0iJ7+ix+P//WDHAWkiDxAhbXUFcQV1BXkFfw0yJ5+hG+f//uP/////r4oPI/+vdZi4PH4QAAAAAAPMPHvpBVkiNNVoGAABJif5BVUFUVVNIg+xgZEiLBCUoAAAASIlEJFgxwOgh+P//SIXAD4R/AQAASInFugIAAAAx9kiJx+jW9///SInv6K73//9Iie9IicNIhcAPiFEBAADoavj//0iNewHo0ff//0mJxEiFwA+ENAEAAL4BAAAASInpSInaSInH6HL4//9BxgQcAEiJ7+iV+P//SI01OQcAAEyJ5+gW+P//SIXAdAPGAABIjTU2BwAATIn36I/3//9IicVIhcAPhPcAAABIicZMiefoCPj//0iJ7+hQ+P//TInnTI1kJBDok/f//0iNVCQMTInmTIn36PP9//9BicWFwA+FrwAAAEiNNeIGAABMiffoOff//0iJxUiFwA+ElAAAAEiJx0iNFa8GAAC+AQAAADHA6Nf2//+LRCQMhcB0MDHbTI01qQYAAGYPH0QAAEEPtgwcTInyvgEAAABIie8xwEiDwwHopfb//zlcJAx330iJ70iNFX4GAAC+AQAAADHA6In2//9Iie/ooff//0iLRCRYZEgrBCUoAAAAdSBIg8RgRInoW11BXEFdQV7DSInv6Hn3//9Bvf/////r0OhM9///TInnQYPN/+iw9v//671mZi4PH4QAAAAAAA8fAPMPHvpBV0iNNXoEAABBVkFVSYn9QVRVU0iB7GgGAABkSIsEJSgAAABIiYQkWAYAADHA6Dn2//9IhcAPhMABAABmD+/ASYnHSI2cJFACAABJvCMgU0lHOkhNDylEJFBMjTWzBQAASL1BQy1TSEEyNQ8pRCRgDylEJHAPKYQkgAAAAA8phCSQAAAADymEJKAAAAAPKYQksAAAAA8phCTAAAAADymEJNAAAAAPKYQk4AAAAA8phCTwAAAADymEJAABAAAPKYQkEAEAAA8phCQgAQAADymEJDABAAAPKYQkQAEAAA8fgAAAAABMifq+AAQAAEiJ3+iY9f//SIXAdENIi0MISIsTSDHoTDHiSAnQddlmgXsQNjp10UiNtCRiAgAASI18JFC6AAEAAOji9f//TIn2SInH6Ef2///GRARQAOuoTIn/6Aj2//+AfCRQAA+EnwAAAEyNdCQQSI1UJAxMie9MifboqPv//4XAD4WQAAAAi0QkDDHbTI2sJFABAABMjSWOBAAATInthcB0MA8fQABFD7YEHkiJ70yJ4b4BAAAASMfC/////zHASIPDAUiDxQLouvX//zlcJAx31EiNdCRQTInv6Hf1//+FwHUsSIuUJFgGAABkSCsUJSgAAAB1J0iBxGgGAABbXUFcQV1BXkFfw7j+////69S4/f///+vNuP/////rxugk9f//8w8e+kiD7AhIg8QIwwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAIAICDinIUgJS0yMHMg562+5ZCN5pyJ5pWICgAgIOKdjCAlLTIwcyDor7vlj5blpLHotKUKAOKdjCDot6/lvoTkuI3lrZjlnKg6ICVzCgBvcGVuZGlyAPCfk4sg6aqM6K+B55uu5b2VOiAlcwoALmNzdgAlcy8lcwDwn5OLIOmqjOivgeaWh+S7tjogJXMKAOKchSDlhajpg6jpgJrov4cgKCVkLyVkKQoA4p2MICVkLyVkIOaWh+S7tumqjOivgeWksei0pQoAAAAAAAAAICDimqAgICUtMjBzIOaXoOetvuWQjSAo5pen54mI5pys55Sf5oiQKQoAAAAAAAAAICDinYwgJS0yMHMg562+5ZCN5LiN5Yy56YWNIOKAlCDmlbDmja7lj6/og73ooqvnr6HmlLkhCgDnlKjms5U6ICVzIFstcV0gPGZpbGVfb3JfZGlyPgoAACAgLXEgIOWuiemdmeaooeW8jywg5Y+q6L+U5Zue6YCA5Ye656CBOgoAAAAAAAAAACAgICAgICAwPeetvuWQjeacieaViCAgMT3nrb7lkI3ml6DmlYggIDI95peg562+5ZCNICAzPUlP6ZSZ6K+vCgByYgAKIyBTSUc6SE1BQy1TSEEyNTY6AHcAYQAlMDJ4AA0KAAAAAAAAMDEyMzQ1Njc4OWFiY2RlZjAxMjM0NTY3ODlhYmNkZWYwMTIzNDU2Nzg5YWJjZGVmMDEyMzQ1Njc4OWFiY2RlZgAAAAABGwM7UAAAAAkAAADs7f//hAAAAKzv//+sAAAAvO///8QAAABs8f//KAEAANz0//9sAAAAzPX//9wAAACs9v//jAEAALz3///kAQAAnPn//ywCAAAUAAAAAAAAAAF6UgABeBABGwwHCJABAAAUAAAAHAAAAGj0//8mAAAAAEQHEAAAAAAkAAAANAAAAGDt///AAQAAAA4QRg4YSg8LdwiAAD8aOiozJCIAAAAAFAAAAFwAAAD47v//EAAAAAAAAAAAAAAAFAAAAHQAAADw7v//sAEAAAAAAAAAAAAASAAAAIwAAADo9P//0gAAAABCDhCNAkIOGIwDRw4gAksKDhhFDhBCDghDC1oKDhhFDhBCDghHC1oKDhhFDhBCDghHC1oOGEUOEEIOCGAAAADYAAAAPPD//20DAAAARg4QjwJCDhiOA0IOII0EQg4ojAVBDjCGBkEOOIMHSg7wCQMsAQoOOEEOMEEOKEIOIEIOGEIOEEIOCEELApwO+AlCDoAKZg74CUQO8AkAAAAAAABUAAAAPAEAABj1//8GAQAAAEIOEI8CQg4YjgNFDiCNBEwOKIwFQQ4whgZBDjiDB0QOQAKdDkhIDlBgDkhDDkBECg44QQ4wQQ4oQg4gQg4YQg4QQg4IQQsARAAAAJQBAADQ9f//0gEAAABGDhCOAkwOGI0DQg4gjARBDiiGBUEOMIMGRA6QAQOJAQoOMEQOKEEOIEIOGEIOEEIOCEELAAAATAAAANwBAABo9///DAIAAABGDhCPAkkOGI4DQg4gjQRFDiiMBUEOMIYGQQ44gwdHDqANA8gBCg44QQ4wQQ4oQg4gQg4YQg4QQg4IQQsAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADwFwAAAAAAALAXAAAAAAAAAQAAAAAAAABVAQAAAAAAAAEAAAAAAAAAZAEAAAAAAAAMAAAAAAAAAAAQAAAAAAAADQAAAAAAAADcHQAAAAAAABkAAAAAAAAA2DwAAAAAAAAbAAAAAAAAAAgAAAAAAAAAGgAAAAAAAADgPAAAAAAAABwAAAAAAAAACAAAAAAAAAD1/v9vAAAAALADAAAAAAAABQAAAAAAAAAIBwAAAAAAAAYAAAAAAAAA2AMAAAAAAAAKAAAAAAAAALQBAAAAAAAACwAAAAAAAAAYAAAAAAAAABUAAAAAAAAAAAAAAAAAAAADAAAAAAAAAOg+AAAAAAAAAgAAAAAAAACIAgAAAAAAABQAAAAAAAAABwAAAAAAAAAXAAAAAAAAAFgKAAAAAAAABwAAAAAAAACACQAAAAAAAAgAAAAAAAAA2AAAAAAAAAAJAAAAAAAAABgAAAAAAAAAHgAAAAAAAAAIAAAAAAAAAPv//28AAAAAAQAACAAAAAD+//9vAAAAAAAJAAAAAAAA////bwAAAAACAAAAAAAAAPD//28AAAAAvAgAAAAAAAD5//9vAAAAAAMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADoPAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwEAAAAAAAAEAQAAAAAAAAUBAAAAAAAABgEAAAAAAAAHAQAAAAAAAAgBAAAAAAAACQEAAAAAAAAKAQAAAAAAAAsBAAAAAAAADAEAAAAAAAANAQAAAAAAAA4BAAAAAAAADwEAAAAAAAAAARAAAAAAAAEBEAAAAAAAAgEQAAAAAAADARAAAAAAAAQBEAAAAAAABQEQAAAAAAAGARAAAAAAAAcBEAAAAAAACAEQAAAAAAAJARAAAAAAAAoBEAAAAAAACwEQAAAAAAAMARAAAAAAAA0BEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIQAAAAAAAAEdDQzogKFVidW50dSAxMS40LjAtMXVidW50dTF+MjIuMDQuMykgMTEuNC4wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAEAPH/AAAAAAAAAAAAAAAAAAAAAAkAAAABAAQAjAMAAAAAAAAgAAAAAAAAABMAAAAEAPH/AAAAAAAAAAAAAAAAAAAAACAAAAACABAAABgAAAAAAADSAAAAAAAAADEAAAAEAPH/AAAAAAAAAAAAAAAAAAAAADwAAAACABAAQBcAAAAAAAAAAAAAAAAAAD4AAAACABAAcBcAAAAAAAAAAAAAAAAAAFEAAAACABAAsBcAAAAAAAAAAAAAAAAAAGcAAAABABoAKEAAAAAAAAABAAAAAAAAAHMAAAABABYA4DwAAAAAAAAAAAAAAAAAAJoAAAACABAA8BcAAAAAAAAAAAAAAAAAAKYAAAABABUA2DwAAAAAAAAAAAAAAAAAAMUAAAAEAPH/AAAAAAAAAAAAAAAAAAAAAMwAAAACABAA4BgAAAAAAAAGAQAAAAAAADEAAAAEAPH/AAAAAAAAAAAAAAAAAAAAANkAAAABABQAsCQAAAAAAAAAAAAAAAAAAAAAAAAEAPH/AAAAAAAAAAAAAAAAAAAAAOcAAAAAABMANCIAAAAAAAAAAAAAAAAAAPoAAAABABgA6D4AAAAAAAAAAAAAAAAAABABAAABABcA6DwAAAAAAAAAAAAAAAAAAC0CAAAgABkAAEAAAAAAAAAAAAAAAAAAABkBAAASAAAAAAAAAAAAAAAAAAAAAAAAADECAAASABAAEBcAAAAAAAAmAAAAAAAAACsBAAASAAAAAAAAAAAAAAAAAAAAAAAAAEUBAAAgAAAAAAAAAAAAAAAAAAAAAAAAAFQBAAASAAAAAAAAAAAAAAAAAAAAAAAAAGYBAAASAAAAAAAAAAAAAAAAAAAAAAAAAH8BAAASAhEA3B0AAAAAAAAAAAAAAAAAAIUBAAASAAAAAAAAAAAAAAAAAAAAAAAAAJgBAAASAAAAAAAAAAAAAAAAAAAAAAAAAKoBAAASAAAAAAAAAAAAAAAAAAAAAAAAAMMBAAASAAAAAAAAAAAAAAAAAAAAAAAAANUBAAAgAAAAAAAAAAAAAAAAAAAAAAAAAPEBAAARABIAACAAAAAAAAAEAAAAAAAAAAACAAASAAAAAAAAAAAAAAAAAAAAAAAAABECAAAgAAAAAAAAAAAAAAAAAAAAAAAAACsCAAAQABkAAEAAAAAAAAAAAAAAAAAAADgCAAASABAA0BsAAAAAAAAMAgAAAAAAAEQCAAASAAAAAAAAAAAAAAAAAAAAAAAAAFgCAAAiAAAAAAAAAAAAAAAAAAAAAAAAAHMCAAASAAAAAAAAAAAAAAAAAAAAAAAAAIcCAAASAAAAAAAAAAAAAAAAAAAAAAAAAJsCAAARAhkAEEAAAAAAAAAAAAAAAAAAAKcCAAASAAAAAAAAAAAAAAAAAAAAAAAAALoCAAASAAAAAAAAAAAAAAAAAAAAAAAAAM0CAAARAhkACEAAAAAAAAAAAAAAAAAAANoCAAASAAAAAAAAAAAAAAAAAAAAAAAAAOwCAAASAAAAAAAAAAAAAAAAAAAAAAAAAAUDAAASAAAAAAAAAAAAAAAAAAAAAAAAABcDAAAQABoAEEAAAAAAAAAAAAAAAAAAACMDAAASAAAAAAAAAAAAAAAAAAAAAAAAAD4DAAASAAAAAAAAAAAAAAAAAAAAAAAAAFEDAAAQABoAMEAAAAAAAAAAAAAAAAAAAFYDAAASAAAAAAAAAAAAAAAAAAAAAAAAAGkDAAASAAAAAAAAAAAAAAAAAAAAAAAAAH4DAAASAAAAAAAAAAAAAAAAAAAAAAAAAJgDAAARABoAIEAAAAAAAAAIAAAAAAAAAKsDAAASAAAAAAAAAAAAAAAAAAAAAAAAAL8DAAASAAAAAAAAAAAAAAAAAAAAAAAAANoDAAASAAAAAAAAAAAAAAAAAAAAAAAAAO0DAAAQABkAEEAAAAAAAAAAAAAAAAAAAPQDAAASAAAAAAAAAAAAAAAAAAAAAAAAABEEAAASABAA8BkAAAAAAADSAQAAAAAAABsEAAASAAAAAAAAAAAAAAAAAAAAAAAAACsEAAASAAAAAAAAAAAAAAAAAAAAAAAAAD4EAAASABAAoBMAAAAAAABtAwAAAAAAAEMEAAASAgwAABAAAAAAAAAAAAAAAAAAAABTY3J0MS5vAF9fYWJpX3RhZwBjc3ZfdmVyaWZ5LmMAdmVyaWZ5X2FuZF9wcmludABjcnRzdHVmZi5jAGRlcmVnaXN0ZXJfdG1fY2xvbmVzAF9fZG9fZ2xvYmFsX2R0b3JzX2F1eABjb21wbGV0ZWQuMABfX2RvX2dsb2JhbF9kdG9yc19hdXhfZmluaV9hcnJheV9lbnRyeQBmcmFtZV9kdW1teQBfX2ZyYW1lX2R1bW15X2luaXRfYXJyYXlfZW50cnkAc2lnbi5jAGNvbXB1dGVfaG1hYwBfX0ZSQU1FX0VORF9fAF9fR05VX0VIX0ZSQU1FX0hEUgBfR0xPQkFMX09GRlNFVF9UQUJMRV8AX0RZTkFNSUMAZnRlbGxAR0xJQkNfMi4yLjUAX19mcHJpbnRmX2Noa0BHTElCQ18yLjMuNABfX2dtb25fc3RhcnRfXwBmc2Vla0BHTElCQ18yLjIuNQBfX3ByaW50Zl9jaGtAR0xJQkNfMi4zLjQAX2ZpbmkAbWFsbG9jQEdMSUJDXzIuMi41AGZvcGVuQEdMSUJDXzIuMi41AEVWUF9zaGEyNTZAT1BFTlNTTF8zLjAuMABmZ2V0c0BHTElCQ18yLjIuNQBfSVRNX2RlcmVnaXN0ZXJUTUNsb25lVGFibGUAX0lPX3N0ZGluX3VzZWQAZnJlZUBHTElCQ18yLjIuNQBfSVRNX3JlZ2lzdGVyVE1DbG9uZVRhYmxlAF9fZGF0YV9zdGFydAB2ZXJpZnlfZmlsZQBvcGVuZGlyQEdMSUJDXzIuMi41AF9fY3hhX2ZpbmFsaXplQEdMSUJDXzIuMi41AHJlYWRkaXJAR0xJQkNfMi4yLjUAc3RycmNockBHTElCQ18yLjIuNQBfX1RNQ19FTkRfXwBzdHJzdHJAR0xJQkNfMi4yLjUAcmV3aW5kQEdMSUJDXzIuMi41AF9fZHNvX2hhbmRsZQBmcHV0c0BHTElCQ18yLjIuNQBfX3N0cmNweV9jaGtAR0xJQkNfMi4zLjQAZnJlYWRAR0xJQkNfMi4yLjUAX19ic3Nfc3RhcnQAX19zdGFja19jaGtfZmFpbEBHTElCQ18yLjQAc3RyY21wQEdMSUJDXzIuMi41AF9lbmQAZmNsb3NlQEdMSUJDXzIuMi41AGNsb3NlZGlyQEdMSUJDXzIuMi41AF9fc3ByaW50Zl9jaGtAR0xJQkNfMi4zLjQAc3RkZXJyQEdMSUJDXzIuMi41AHN0cmNzcG5AR0xJQkNfMi4yLjUAX19zbnByaW50Zl9jaGtAR0xJQkNfMi4zLjQAcGVycm9yQEdMSUJDXzIuMi41AF9lZGF0YQBfX2xpYmNfc3RhcnRfbWFpbkBHTElCQ18yLjM0AHNpZ25fZmlsZQBzdGF0QEdMSUJDXzIuMzMASE1BQ0BPUEVOU1NMXzMuMC4wAG1haW4AX2luaXQAAC5zeW10YWIALnN0cnRhYgAuc2hzdHJ0YWIALmludGVycAAubm90ZS5nbnUucHJvcGVydHkALm5vdGUuZ251LmJ1aWxkLWlkAC5ub3RlLkFCSS10YWcALmdudS5oYXNoAC5keW5zeW0ALmR5bnN0cgAuZ251LnZlcnNpb24ALmdudS52ZXJzaW9uX3IALnJlbGEuZHluAC5yZWxhLnBsdAAuaW5pdAAucGx0LmdvdAAucGx0LnNlYwAudGV4dAAuZmluaQAucm9kYXRhAC5laF9mcmFtZV9oZHIALmVoX2ZyYW1lAC5pbml0X2FycmF5AC5maW5pX2FycmF5AC5keW5hbWljAC5kYXRhAC5ic3MALmNvbW1lbnQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGwAAAAEAAAACAAAAAAAAABgDAAAAAAAAGAMAAAAAAAAcAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAACMAAAAHAAAAAgAAAAAAAAA4AwAAAAAAADgDAAAAAAAAMAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAA2AAAABwAAAAIAAAAAAAAAaAMAAAAAAABoAwAAAAAAACQAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAASQAAAAcAAAACAAAAAAAAAIwDAAAAAAAAjAMAAAAAAAAgAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAFcAAAD2//9vAgAAAAAAAACwAwAAAAAAALADAAAAAAAAKAAAAAAAAAAGAAAAAAAAAAgAAAAAAAAAAAAAAAAAAABhAAAACwAAAAIAAAAAAAAA2AMAAAAAAADYAwAAAAAAADADAAAAAAAABwAAAAEAAAAIAAAAAAAAABgAAAAAAAAAaQAAAAMAAAACAAAAAAAAAAgHAAAAAAAACAcAAAAAAAC0AQAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAHEAAAD///9vAgAAAAAAAAC8CAAAAAAAALwIAAAAAAAARAAAAAAAAAAGAAAAAAAAAAIAAAAAAAAAAgAAAAAAAAB+AAAA/v//bwIAAAAAAAAAAAkAAAAAAAAACQAAAAAAAIAAAAAAAAAABwAAAAIAAAAIAAAAAAAAAAAAAAAAAAAAjQAAAAQAAAACAAAAAAAAAIAJAAAAAAAAgAkAAAAAAADYAAAAAAAAAAYAAAAAAAAACAAAAAAAAAAYAAAAAAAAAJcAAAAEAAAAQgAAAAAAAABYCgAAAAAAAFgKAAAAAAAAiAIAAAAAAAAGAAAAGAAAAAgAAAAAAAAAGAAAAAAAAAChAAAAAQAAAAYAAAAAAAAAABAAAAAAAAAAEAAAAAAAABsAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAnAAAAAEAAAAGAAAAAAAAACAQAAAAAAAAIBAAAAAAAADAAQAAAAAAAAAAAAAAAAAAEAAAAAAAAAAQAAAAAAAAAKcAAAABAAAABgAAAAAAAADgEQAAAAAAAOARAAAAAAAAEAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAEAAAAAAAAACwAAAAAQAAAAYAAAAAAAAA8BEAAAAAAADwEQAAAAAAALABAAAAAAAAAAAAAAAAAAAQAAAAAAAAABAAAAAAAAAAuQAAAAEAAAAGAAAAAAAAAKATAAAAAAAAoBMAAAAAAAA8CgAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAL8AAAABAAAABgAAAAAAAADcHQAAAAAAANwdAAAAAAAADQAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAADFAAAAAQAAAAIAAAAAAAAAACAAAAAAAAAAIAAAAAAAADECAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAzQAAAAEAAAACAAAAAAAAADQiAAAAAAAANCIAAAAAAABUAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAANsAAAABAAAAAgAAAAAAAACIIgAAAAAAAIgiAAAAAAAALAIAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAADlAAAADgAAAAMAAAAAAAAA2DwAAAAAAADYLAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAgAAAAAAAAA8QAAAA8AAAADAAAAAAAAAOA8AAAAAAAA4CwAAAAAAAAIAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAIAAAAAAAAAP0AAAAGAAAAAwAAAAAAAADoPAAAAAAAAOgsAAAAAAAAAAIAAAAAAAAHAAAAAAAAAAgAAAAAAAAAEAAAAAAAAACrAAAAAQAAAAMAAAAAAAAA6D4AAAAAAADoLgAAAAAAABgBAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAgAAAAAAAAABgEAAAEAAAADAAAAAAAAAABAAAAAAAAAADAAAAAAAAAQAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAwBAAAIAAAAAwAAAAAAAAAgQAAAAAAAABAwAAAAAAAAEAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAARAQAAAQAAADAAAAAAAAAAAAAAAAAAAAAQMAAAAAAAAC0AAAAAAAAAAAAAAAAAAAABAAAAAAAAAAEAAAAAAAAAAQAAAAIAAAAAAAAAAAAAAAAAAAAAAAAAQDAAAAAAAABgBgAAAAAAAB0AAAAVAAAACAAAAAAAAAAYAAAAAAAAAAkAAAADAAAAAAAAAAAAAAAAAAAAAAAAAKA2AAAAAAAASQQAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAARAAAAAwAAAAAAAAAAAAAAAAAAAAAAAADpOgAAAAAAABoBAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAA"""

def _get_csv_verify():
    """解码内嵌二进制, 缓存到 /tmp, 复用时跳过解码"""
    cache = '/tmp/.tbox_csv_verify_cached'
    try:
        b64 = _CSV_B64.strip()
        if len(b64) < 100:
            raise ValueError('not embedded')
        binary = base64.b64decode(b64)
        if os.path.exists(cache) and os.path.getsize(cache) == len(binary):
            return cache
        with open(cache, 'wb') as f:
            f.write(binary)
        os.chmod(cache, 0o755)
        return cache
    except Exception:
        return os.path.join(os.path.dirname(os.path.abspath(__file__)),
                            '..', 'src', 'build', 'csv_verify')

CSV_VERIFY_BIN = _get_csv_verify()


def verify_csv_signature(path):
    try:
        r = subprocess.run([CSV_VERIFY_BIN, '-q', path],
                           capture_output=True, timeout=5)
        if r.returncode == 0:    return True, None
        elif r.returncode == 2:  return None, None
        else:                    return False, r.stderr.decode().strip() or "签名验证失败"
    except FileNotFoundError:
        return 'no_binary', None
    except Exception as e:
        return None, str(e)


def read_csv(path):
    rows = []
    with open(path, 'r') as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith('#'):
                continue
            parts = line.split(',')
            try:
                val = float(parts[1]) if len(parts) > 1 else float(parts[0])
                rows.append(val)
            except (ValueError, IndexError):
                pass
    return rows


def read_csv_multi(path):
    a, b = [], []
    with open(path, 'r') as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith('#'):
                continue
            parts = line.split(',')
            try:
                if len(parts) >= 3:
                    a.append(float(parts[1]))
                    b.append(float(parts[2]))
            except (ValueError, IndexError):
                pass
    return a, b


class BarChart(tk.Canvas):
    COLORS = {
        'cpu': '#58a6ff', 'mem': '#3fb950', 'thr': '#f0883e',
        'fd': '#d2a8ff', 'ior': '#f85149', 'iow': '#f59e0b',
    }

    def __init__(self, parent, title, data, color_key, sig_ok, **kw):
        w = kw.pop('width', 460)
        h = kw.pop('height', 220)
        super().__init__(parent, width=w, height=h, bg='#161b22',
                         highlightthickness=1, highlightbackground='#30363d', **kw)
        self.title = title
        self.data = data
        self.color = self.COLORS.get(color_key, '#888')
        self.sig_ok = sig_ok
        self._draw()

    def _draw(self):
        self.delete('all')
        w = int(self['width']); h = int(self['height'])
        ml, mr, mb = 48, 16, 32

        if not self.data:
            self.create_text(w//2, h//2, text='No data', fill='#888', font=('', 11))
            return

        ys = self.data
        ymax = max(ys)
        if ymax == 0: ymax = 1
        if ymax <= 10:   ymax = int(ymax) + 1
        elif ymax <= 100: ymax = ((int(ymax)//10)+1)*10
        else:             ymax = ((int(ymax)//100)+1)*100

        ty = 12
        if self.sig_ok is False:
            self.create_rectangle(0, 0, w, 20, fill='#3d1115', outline='')
            self.create_text(w//2, 12, text='⚠ 签名无效 — 数据可能被篡改',
                             fill='#f85149', font=('', 9, 'bold'))
            ty = 30
        elif self.sig_ok is None:
            self.create_rectangle(0, 0, w, 20, fill='#332810', outline='')
            self.create_text(w//2, 12, text='⚠ 无签名 — 无法核实真伪',
                             fill='#d2991d', font=('', 9, 'bold'))
            ty = 30
        elif self.sig_ok == 'no_binary':
            self.create_rectangle(0, 0, w, 20, fill='#332810', outline='')
            self.create_text(w//2, 12, text='⚠ 无法验签 — 验签工具未找到',
                             fill='#d2991d', font=('', 9, 'bold'))
            ty = 30

        self.create_text(w//2, ty, text=self.title, fill='#ccc', font=('', 11, 'bold'))
        mt = ty + 14; ph = h - mt - mb

        def tx(i): return ml + i / max(1, len(ys)) * (w - ml - mr)
        def ty_(v): return h - mb - (v / ymax) * ph

        for i in range(5):
            gy = h - mb - ph * i / 4
            self.create_line(ml, gy, w-mr, gy, fill='#333', dash=(3,3))
        for i in range(5):
            val = ymax * i / 4
            gy = h - mb - ph * i / 4
            self.create_text(ml-6, gy, text=f'{val:.0f}', fill='#888', font=('', 8), anchor='e')

        self.create_line(ml, h-mb, w-mr, h-mb, fill='#555')
        self.create_line(ml, mt, ml, h-mb, fill='#555')

        n = len(ys); gap = (w - ml - mr) / n; bar_w = max(3, gap * 0.6)
        for i, y in enumerate(ys):
            bx = ml + gap * i + (gap - bar_w) / 2
            by = ty_(y); bh = max(1, ty_(0) - ty_(y))
            self.create_rectangle(bx, by, bx+bar_w, by+bh, fill=self.color, outline='')

        step = max(1, n // 8)
        for i in range(0, n, step):
            bx = ml + gap * i + gap/2
            self.create_text(bx, h-mb+12, text=str(i+1), fill='#888', font=('', 8), anchor='n')
        if n > 1 and (n-1) % step != 0:
            bx = ml + gap * (n-1) + gap/2
            self.create_text(bx, h-mb+12, text=str(n), fill='#888', font=('', 8), anchor='n')


class App(tk.Tk):
    def __init__(self, profile_dir):
        super().__init__()
        self.title("TBox Resource Profile")
        self.configure(bg='#0d1117')

        proc_name = "unknown"
        rpt_path = os.path.join(profile_dir, "report.txt")
        if os.path.exists(rpt_path):
            with open(rpt_path) as f:
                for line in f:
                    if "进程名称:" in line:
                        proc_name = line.split(":")[-1].strip()

        header = tk.Frame(self, bg='#0d1117')
        header.pack(fill='x', padx=16, pady=(12, 4))
        tk.Label(header, text=f"TBox Resource Profile — {proc_name}",
                 fg='#f0f6fc', bg='#0d1117', font=('', 13, 'bold')).pack(anchor='w')
        tk.Label(header, text=f"Data: {profile_dir}",
                 fg='#8b949e', bg='#0d1117', font=('', 8)).pack(anchor='w')

        grid = tk.Frame(self, bg='#0d1117')
        grid.pack(fill='both', expand=True, padx=12, pady=8)

        def csv_path(f): return os.path.join(profile_dir, f)
        cpu_data = read_csv(csv_path('cpu.csv'))
        mem_data = read_csv(csv_path('mem.csv'))
        thr_data, fd_data = read_csv_multi(csv_path('threads_fd.csv'))
        ior_data, iow_data = read_csv_multi(csv_path('io.csv'))

        def sig(fname):
            r = verify_csv_signature(csv_path(fname))
            return r[0] if r else None

        charts = [
            ('CPU Usage (%)',         cpu_data,  'cpu',  sig('cpu.csv')),
            ('Memory RSS (KB)',       mem_data,  'mem',  sig('mem.csv')),
            ('Thread Count',          thr_data,  'thr',  sig('threads_fd.csv')),
            ('Open File Descriptors', fd_data,   'fd',   sig('threads_fd.csv')),
            ('IO Read (KB/s)',        ior_data,  'ior',  sig('io.csv')),
            ('IO Write (KB/s)',       iow_data,  'iow',  sig('io.csv')),
        ]
        for i, (title, data, ck, sig_ok) in enumerate(charts):
            chart = BarChart(grid, title, data, ck, sig_ok, width=420, height=200)
            chart.grid(row=i//2, column=i%2, padx=6, pady=6, sticky='nsew')
            grid.grid_columnconfigure(i%2, weight=1)
            grid.grid_rowconfigure(i//2, weight=1)

        footer = tk.Frame(self, bg='#0d1117')
        footer.pack(fill='x', padx=16, pady=(0, 8))
        tk.Label(footer, text="plot_gui.py — TBox Resource Monitor Toolkit",
                 fg='#8b949e', bg='#0d1117', font=('', 7)).pack(side='left')

        self.bind('<Control-q>', lambda e: self.destroy())
        self.bind('<Escape>', lambda e: self.destroy())
        self.update_idletasks()
        self.geometry(f"{max(900, self.winfo_reqwidth())}x{max(680, self.winfo_reqheight())}")
        self.minsize(780, 560)


if __name__ == '__main__':
    if len(sys.argv) < 2:
        print(f"用法: {sys.argv[0]} <profile_dir>")
        sys.exit(1)
    d = sys.argv[1]
    if not os.path.isdir(d):
        print(f"❌ 目录不存在: {d}")
        sys.exit(1)
    app = App(d)
    app.mainloop()
